#ifndef WASMOS_DRIVER_ABI_H
#define WASMOS_DRIVER_ABI_H

#include <stdint.h>

#define CONSOLE_RING_DATA_SIZE 4080u

typedef struct {
    volatile uint32_t write_pos;
    volatile uint32_t read_pos;
    uint32_t capacity;
    uint32_t _pad;
    uint8_t data[CONSOLE_RING_DATA_SIZE];
} console_ring_t;

enum {
    WASM_CHARDEV_IPC_READ_REQ = 0x100,
    WASM_CHARDEV_IPC_WRITE_REQ = 0x101,
    WASM_CHARDEV_IPC_READ_RESP = 0x180,
    WASM_CHARDEV_IPC_WRITE_RESP = 0x181,
    WASM_CHARDEV_IPC_ERROR_RESP = 0x1FF
};

enum {
    PROC_IPC_SPAWN = 0x200,
    PROC_IPC_WAIT = 0x201,
    PROC_IPC_KILL = 0x202,
    PROC_IPC_STATUS = 0x203,
    PROC_IPC_SPAWN_NAME = 0x204,
    PROC_IPC_RESP = 0x280,
    PROC_IPC_ERROR = 0x2FF
};

enum {
    PROC_STATUS_UNKNOWN = 0,
    PROC_STATUS_RUNNING = 1,
    PROC_STATUS_ZOMBIE = 2
};

enum {
    BLOCK_IPC_READ_REQ = 0x300,
    BLOCK_IPC_WRITE_REQ = 0x301,
    BLOCK_IPC_IDENTIFY_REQ = 0x302,
    BLOCK_IPC_READ_RESP = 0x380,
    BLOCK_IPC_WRITE_RESP = 0x381,
    BLOCK_IPC_IDENTIFY_RESP = 0x382,
    BLOCK_IPC_ERROR = 0x3FF
};

enum {
    FS_IPC_OPEN_REQ = 0x400,
    FS_IPC_READ_REQ = 0x401,
    FS_IPC_CLOSE_REQ = 0x402,
    FS_IPC_STAT_REQ = 0x403,
    FS_IPC_READY_REQ = 0x404,
    FS_IPC_SEEK_REQ = 0x405,
    FS_IPC_WRITE_REQ = 0x406,
    FS_IPC_UNLINK_REQ = 0x407,
    FS_IPC_MKDIR_REQ = 0x408,
    FS_IPC_RMDIR_REQ = 0x409,
    FS_IPC_LIST_ROOT_REQ = 0x410,
    FS_IPC_CAT_ROOT_REQ = 0x411,
    FS_IPC_CHDIR_REQ = 0x412,
    FS_IPC_READ_APP_REQ = 0x413,
    FS_IPC_RESP = 0x480,
    FS_IPC_ERROR = 0x4FF
};

enum {
    FBTEXT_IPC_CELL_WRITE_REQ  = 0x600,
    FBTEXT_IPC_CURSOR_SET_REQ  = 0x601,
    FBTEXT_IPC_SCROLL_REQ      = 0x602,
    FBTEXT_IPC_CLEAR_REQ       = 0x603,
    FBTEXT_IPC_RESP            = 0x680,
    FBTEXT_IPC_ERROR           = 0x6FF
};

enum {
    VT_IPC_WRITE_REQ    = 0x700,
    VT_IPC_READ_REQ     = 0x701,
    VT_IPC_SET_ATTR_REQ = 0x702,
    VT_IPC_SWITCH_TTY   = 0x703,
    VT_IPC_RESP         = 0x780,
    VT_IPC_ERROR        = 0x7FF
};

enum {
    KBD_IPC_SUBSCRIBE_REQ  = 0x800,
    KBD_IPC_SUBSCRIBE_RESP = 0x880,
    KBD_IPC_KEY_NOTIFY     = 0x801
};

enum {
    WASMOS_IPC_FIELD_TYPE = 0,
    WASMOS_IPC_FIELD_REQUEST_ID = 1,
    WASMOS_IPC_FIELD_ARG0 = 2,
    WASMOS_IPC_FIELD_ARG1 = 3,
    WASMOS_IPC_FIELD_SOURCE = 4,
    WASMOS_IPC_FIELD_DESTINATION = 5,
    WASMOS_IPC_FIELD_ARG2 = 6,
    WASMOS_IPC_FIELD_ARG3 = 7
};

#endif
