#ifndef WASMOS_DRIVER_ABI_H
#define WASMOS_DRIVER_ABI_H

#include <stdint.h>

enum {
    WASM_CHARDEV_IPC_READ_REQ = 0x100,
    WASM_CHARDEV_IPC_WRITE_REQ = 0x101,
    WASM_CHARDEV_IPC_READ_RESP = 0x180,
    WASM_CHARDEV_IPC_WRITE_RESP = 0x181,
    WASM_CHARDEV_IPC_ERROR_RESP = 0x1FF
};

enum {
    PROC_IPC_SPAWN = 0x200,
    PROC_IPC_WAIT = 0x201,
    PROC_IPC_KILL = 0x202,
    PROC_IPC_STATUS = 0x203,
    PROC_IPC_SPAWN_NAME = 0x204,
    PROC_IPC_RESP = 0x280,
    PROC_IPC_ERROR = 0x2FF
};

enum {
    PROC_STATUS_UNKNOWN = 0,
    PROC_STATUS_RUNNING = 1,
    PROC_STATUS_ZOMBIE = 2
};

enum {
    BLOCK_IPC_READ_REQ = 0x300,
    BLOCK_IPC_WRITE_REQ = 0x301,
    BLOCK_IPC_IDENTIFY_REQ = 0x302,
    BLOCK_IPC_READ_RESP = 0x380,
    BLOCK_IPC_WRITE_RESP = 0x381,
    BLOCK_IPC_IDENTIFY_RESP = 0x382,
    BLOCK_IPC_ERROR = 0x3FF
};

enum {
    FS_IPC_OPEN_REQ = 0x400,
    FS_IPC_READ_REQ = 0x401,
    FS_IPC_CLOSE_REQ = 0x402,
    FS_IPC_STAT_REQ = 0x403,
    FS_IPC_LIST_ROOT_REQ = 0x410,
    FS_IPC_CAT_ROOT_REQ = 0x411,
    FS_IPC_CHDIR_REQ = 0x412,
    FS_IPC_READ_APP_REQ = 0x413,
    FS_IPC_RESP = 0x480,
    FS_IPC_ERROR = 0x4FF
};

enum {
    WASMOS_IPC_FIELD_TYPE = 0,
    WASMOS_IPC_FIELD_REQUEST_ID = 1,
    WASMOS_IPC_FIELD_ARG0 = 2,
    WASMOS_IPC_FIELD_ARG1 = 3,
    WASMOS_IPC_FIELD_SOURCE = 4,
    WASMOS_IPC_FIELD_DESTINATION = 5,
    WASMOS_IPC_FIELD_ARG2 = 6,
    WASMOS_IPC_FIELD_ARG3 = 7
};

#endif
