#ifndef WASMOS_DRIVER_ABI_H
#define WASMOS_DRIVER_ABI_H

#include <stdint.h>

enum {
    WASM_CHARDEV_IPC_READ_REQ = 0x100,
    WASM_CHARDEV_IPC_WRITE_REQ = 0x101,
    WASM_CHARDEV_IPC_READ_RESP = 0x180,
    WASM_CHARDEV_IPC_WRITE_RESP = 0x181,
    WASM_CHARDEV_IPC_ERROR_RESP = 0x1FF
};

enum {
    PROC_IPC_SPAWN = 0x200,
    PROC_IPC_WAIT = 0x201,
    PROC_IPC_KILL = 0x202,
    PROC_IPC_STATUS = 0x203,
    PROC_IPC_RESP = 0x280,
    PROC_IPC_ERROR = 0x2FF
};

enum {
    PROC_STATUS_UNKNOWN = 0,
    PROC_STATUS_RUNNING = 1,
    PROC_STATUS_ZOMBIE = 2
};

enum {
    WASMOS_IPC_FIELD_TYPE = 0,
    WASMOS_IPC_FIELD_REQUEST_ID = 1,
    WASMOS_IPC_FIELD_ARG0 = 2,
    WASMOS_IPC_FIELD_ARG1 = 3,
    WASMOS_IPC_FIELD_SOURCE = 4,
    WASMOS_IPC_FIELD_DESTINATION = 5
};

enum {
    WASMOS_WASM_STEP_YIELDED = 0,
    WASMOS_WASM_STEP_BLOCKED = 1,
    WASMOS_WASM_STEP_DONE = 2,
    WASMOS_WASM_STEP_FAILED = -1
};

#endif
