#!/usr/bin/env python3

import argparse
import subprocess
import sys


def c_bytes_literal(data: bytes) -> str:
    chunks = []
    for i in range(0, len(data), 16):
        piece = "".join(f"\\x{b:02x}" for b in data[i : i + 16])
        chunks.append(f'    "{piece}"')
    return "\n".join(chunks) if chunks else '    ""'


def collect_symbols(nm_path: str, input_path: str):
    proc = subprocess.run(
        [nm_path, "--defined-only", "-n", input_path],
        check=True,
        capture_output=True,
        text=True,
    )
    symbols = []
    for line in proc.stdout.splitlines():
        parts = line.strip().split(maxsplit=2)
        if len(parts) != 3:
            continue
        addr_str, sym_type, name = parts
        if sym_type not in {"t", "T", "w", "W"}:
            continue
        if name.startswith(".L"):
            continue
        try:
            addr = int(addr_str, 16)
        except ValueError:
            continue
        symbols.append((addr, name))
    filtered = []
    last_addr = None
    last_name = None
    for addr, name in symbols:
        if addr == last_addr and name == last_name:
            continue
        filtered.append((addr, name))
        last_addr = addr
        last_name = name
    return filtered


def emit_source(symbols, output_path: str):
    names_blob = bytearray()
    entries = []
    for addr, name in symbols:
        off = len(names_blob)
        names_blob.extend(name.encode("utf-8"))
        names_blob.append(0)
        entries.append((addr, off))

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by gen_kernel_kallsyms.py. */\n")
        f.write("#include \"kallsyms.h\"\n")
        f.write("\n")
        f.write("typedef struct {\n")
        f.write("    uint64_t addr;\n")
        f.write("    uint32_t name_off;\n")
        f.write("} kernel_kallsyms_entry_t;\n\n")
        f.write("const char g_kernel_kallsyms_names[] =\n")
        f.write(c_bytes_literal(bytes(names_blob)))
        f.write(";\n\n")
        f.write("const kernel_kallsyms_entry_t g_kernel_kallsyms[] = {\n")
        for addr, off in entries:
            f.write(f"    {{ 0x{addr:016x}ULL, {off}u }},\n")
        f.write("};\n\n")
        f.write(f"const uint32_t g_kernel_kallsyms_count = {len(entries)}u;\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--nm", required=True)
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    symbols = collect_symbols(args.nm, args.input)
    if not symbols:
        print("no kernel text symbols found", file=sys.stderr)
        return 1
    emit_source(symbols, args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
