#!/usr/bin/env python3
"""Generate the WASMOS value-constant ABI from abi/constants.yaml.

The third axis of the ABI: abi/opcodes.yaml owns the positive `type` field of a
message, abi/errors.yaml the negative packed status codes, and this IDL owns the
plain VALUES a peer passes or interprets -- socket families and types, flag bits,
structure versions, size ceilings.

It exists because the other two were generated for every language while the
values used WITH them were not. An app could name NET_IPC_SOCKET_OPEN in Rust,
Go, Zig or AssemblyScript but had to hard-code the family and type it puts in the
open descriptor, because those were a C enum in wasmos_driver_abi.h that only C
can include.

Generates:
  - abi/generated/c/wasmos_constants.h            one enum per group
  - abi/generated/docs/constants.md               per-group reference tables
  - abi/generated/{rust,go,zig,assemblyscript}/wasmos_constants.*

Values are emitted in the form the IDL gives them: a group marked `bits: true`
keeps hex, so a flag stays readable as a flag rather than becoming a decimal a
reader has to convert back.

Usage:
    gen_abi_constants.py [--check] [--verify-source]
      (no args)        regenerate all generated constant files
      --check          fail (exit 2) if any on-disk file differs from the IDL
      --verify-source  fail (exit 3) if the IDL does not reproduce the live
                       constants in wasmos_driver_abi.h (symbol -> value)
"""

import argparse
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IDL_PATH = os.path.join(REPO_ROOT, "abi", "constants.yaml")
GEN_ROOT = os.path.join(REPO_ROOT, "abi", "generated")
CONSTANTS_H = os.path.join(GEN_ROOT, "c", "wasmos_constants.h")
CONSTANTS_MD = os.path.join(GEN_ROOT, "docs", "constants.md")
RUST_OUT = os.path.join(GEN_ROOT, "rust", "wasmos_constants.rs")
GO_OUT = os.path.join(GEN_ROOT, "go", "wasmos_constants.go")
ZIG_OUT = os.path.join(GEN_ROOT, "zig", "wasmos_constants.zig")
AS_OUT = os.path.join(GEN_ROOT, "assemblyscript", "wasmos_constants.ts")

DRIVER_ABI_H = os.path.join(
    REPO_ROOT, "src", "drivers", "include", "wasmos_driver_abi.h"
)

_GEN = "GENERATED by scripts/gen_abi_constants.py from abi/constants.yaml — DO NOT EDIT."
_REF = "See docs/architecture/34-abi-idl-and-error-model.md."

BANNER = [
    "/* " + _GEN,
    " *",
    " * " + _REF,
    " */",
]


def die(msg, code=1):
    print(f"gen_abi_constants: {msg}", file=sys.stderr)
    sys.exit(code)


class YamlUnavailable(RuntimeError):
    pass


def load_idl():
    try:
        import yaml
    except ImportError as exc:
        raise YamlUnavailable(
            "PyYAML is required to regenerate the constant ABI (pip install pyyaml); "
            "the checked-in generated files are used for normal builds."
        ) from exc
    with open(IDL_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


class Model:
    def __init__(self, idl):
        self.version = int(idl["abi_version"])
        self.groups = idl["groups"]
        self.symbols = {}
        for g in self.groups:
            for c in g["constants"]:
                sym = c["symbol"]
                if sym in self.symbols:
                    die(f"duplicate symbol {sym}")
                self.symbols[sym] = int(c["value"])

    @staticmethod
    def fmt(group, const):
        """Render a value the way the IDL wrote it: hex for a flag group so a bit
        stays legible, decimal otherwise."""
        return (
            f"0x{int(const['value']):X}" if group.get("bits") else str(int(const["value"]))
        )


def _doc_block(text, indent):
    if not text:
        return []
    lines = text.rstrip("\n").split("\n") if isinstance(text, str) else list(text)
    if len(lines) == 1:
        return [f"{indent}/* {lines[0]} */"]
    out = [f"{indent}/* {lines[0]}"]
    out += [f"{indent} * {ln}".rstrip() for ln in lines[1:]]
    out.append(f"{indent} */")
    return out


def _doc_lines(text, prefix):
    if not text:
        return []
    lines = text.rstrip("\n").split("\n") if isinstance(text, str) else list(text)
    return [f"{prefix} {ln}".rstrip() for ln in lines]


def emit_constants_h(m):
    o = list(BANNER)
    w = o.append
    w("#ifndef WASMOS_GENERATED_CONSTANTS_H")
    w("#define WASMOS_GENERATED_CONSTANTS_H")
    w("")
    w("/* Value constants of the ABI, one enum per group. An enum rather than a")
    w(" * macro so the names survive into debug info and a switch on one can be")
    w(" * checked for exhaustiveness. */")
    for g in m.groups:
        w("")
        o.extend(_doc_block(g.get("doc"), ""))
        w("enum {")
        for c in g["constants"]:
            o.extend(_doc_block(c.get("doc"), "    "))
            w(f"    {c['symbol']} = {Model.fmt(g, c)},")
        w("};")
    w("")
    w("#endif /* WASMOS_GENERATED_CONSTANTS_H */")
    w("")
    return "\n".join(o)


def emit_constants_md(m):
    o = [f"<!-- {_GEN} -->", "", "# WASMOS Value Constants", ""]
    o.append(
        "Values a peer passes or interprets, generated from `abi/constants.yaml` "
        "into C, Rust, Go, Zig and AssemblyScript."
    )
    for g in m.groups:
        o += ["", f"## {g['name']}", ""]
        if g.get("doc"):
            o += [g["doc"].rstrip("\n"), ""]
        if g.get("bits"):
            o += ["Flag bits: members are OR-able rather than alternatives.", ""]
        o += ["| Symbol | Value | Meaning |", "| --- | --- | --- |"]
        for c in g["constants"]:
            doc = " ".join((c.get("doc") or "").split())
            o.append(f"| `{c['symbol']}` | {Model.fmt(g, c)} | {doc} |")
    o.append("")
    return "\n".join(o)


def _lang(m, hdr, group_fmt, const_fmt, doc_prefix):
    """Shared per-language emitter: constants grouped exactly as the IDL groups
    them, each keeping the C symbol name so a value is greppable across
    languages."""
    o = [f"// {_GEN}", f"// {_REF}", ""] + list(hdr)
    for g in m.groups:
        o.append("")
        o.append(group_fmt(g["name"], g.get("bits", False)))
        o.extend(_doc_lines(g.get("doc"), doc_prefix))
        for c in g["constants"]:
            o.extend(_doc_lines(c.get("doc"), doc_prefix))
            o.append(const_fmt(c["symbol"], Model.fmt(g, c)))
    o.append("")
    return "\n".join(o)


def _group_comment(name, bits):
    return f"// {name}" + (" (flag bits)" if bits else "")


def emit_rust(m):
    return _lang(
        m,
        ["#![allow(dead_code)]"],
        _group_comment,
        lambda sym, v: f"pub const {sym}: i32 = {v};",
        "///",
    )


def emit_go(m):
    return _lang(
        m,
        ["package wasmos"],
        _group_comment,
        lambda sym, v: f"const {sym} int32 = {v}",
        "//",
    )


def emit_zig(m):
    return _lang(
        m,
        [],
        _group_comment,
        lambda sym, v: f"pub const {sym}: i32 = {v};",
        "///",
    )


def emit_as(m):
    return _lang(
        m,
        [],
        _group_comment,
        lambda sym, v: f"export const {sym}: i32 = {v};",
        "//",
    )


OUTPUTS = [
    (CONSTANTS_H, emit_constants_h),
    (CONSTANTS_MD, emit_constants_md),
    (RUST_OUT, emit_rust),
    (GO_OUT, emit_go),
    (ZIG_OUT, emit_zig),
    (AS_OUT, emit_as),
]


def _read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def verify_source(m):
    """Assert the live wasmos_driver_abi.h reproduces the IDL symbol->value map
    for every symbol the IDL names. Self-skips once the header is swapped to
    #include the generated enums."""
    text = _read(DRIVER_ABI_H)
    if "wasmos_constants.h" in text:
        print(
            "gen_abi_constants: header already swapped to the generated enums; "
            "--check guards it"
        )
        return
    src = {}
    for sym, val in re.findall(r"#define\s+([A-Z][A-Z0-9_]+)\s+(0x[0-9A-Fa-f]+|\d+)u?", text):
        src[sym] = int(val, 0)
    for sym, val in re.findall(r"([A-Z][A-Z0-9_]+)\s*=\s*(0x[0-9A-Fa-f]+|\d+)\s*[,}]", text):
        src.setdefault(sym, int(val, 0))
    problems = []
    for sym, want in m.symbols.items():
        if sym not in src:
            problems.append(f"{sym} is in the IDL but not in the header")
        elif src[sym] != want:
            problems.append(f"value mismatch {sym}: src={src[sym]} idl={want}")
    if problems:
        for p in problems:
            print(f"gen_abi_constants: {p}", file=sys.stderr)
        die("IDL does not match the live constants — reconcile before generating", code=3)
    print(
        f"gen_abi_constants: IDL verified against wasmos_driver_abi.h "
        f"({len(m.symbols)} constants across {len(m.groups)} groups)"
    )


def main():
    ap = argparse.ArgumentParser(description="Generate the WASMOS value-constant ABI.")
    ap.add_argument(
        "--check", action="store_true", help="fail if any generated file is stale"
    )
    ap.add_argument(
        "--verify-source",
        action="store_true",
        help="fail if the IDL ≠ the live constants",
    )
    args = ap.parse_args()

    try:
        model = Model(load_idl())
    except YamlUnavailable as exc:
        if args.check or args.verify_source:
            print(f"gen_abi_constants: skipping ({exc})", file=sys.stderr)
            return
        die(str(exc))

    if args.verify_source:
        verify_source(model)
        return

    if args.check:
        stale = False
        for path, emit in OUTPUTS:
            want = emit(model)
            have = _read(path) if os.path.exists(path) else None
            if have != want:
                print(
                    f"gen_abi_constants: {os.path.relpath(path, REPO_ROOT)} is stale",
                    file=sys.stderr,
                )
                stale = True
        if stale:
            die("run scripts/gen_abi_constants.py to regenerate", code=2)
        print("gen_abi_constants: all generated constant files are up to date")
        return

    for path, emit in OUTPUTS:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(emit(model))
        print(f"gen_abi_constants: wrote {os.path.relpath(path, REPO_ROOT)}")


if __name__ == "__main__":
    main()
