#!/usr/bin/env python3
"""Generate the wasmos error/status ABI from abi/errors.yaml for every language.

Single source of truth -> generated value-ABI per language. The generated files
live under abi/generated/<lang>/ (kept out of the src/ format+lint scope so their
formatters cannot fight the byte-exact --check guard). The runtime/IPC wrappers
that USE these codes live in src/libsys/{wasm,native}; see
docs/architecture/34-abi-idl-and-error-model.md.

Every language gets the full value ABI: constants + packed accessors + decode
lookups + the fixed error object and chain helpers (wrap/unwrap/is/as/root).
C/Rust/Zig/Go use a C-layout struct; AssemblyScript (which has no C-layout value
struct) gets pointer-based helpers over the 40-byte block. Only the IPC framing
(serialize the block to/from a reply payload) lives in the libsys wrappers.

Usage:
    gen_abi_errors.py [--check] [--lang LANG]
      (no args)  regenerate every language file in place
      --lang     restrict to one language (c|rust|go|zig|assemblyscript)
      --check    fail (exit 2) if any on-disk file differs from the IDL;
                 skips (exit 0) when PyYAML is unavailable
"""

import argparse
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IDL_PATH = os.path.join(REPO_ROOT, "abi", "errors.yaml")
GEN_ROOT = os.path.join(REPO_ROOT, "abi", "generated")

CHAIN_DEPTH = 4
ERROR_OBJ_BYTES = 4 + 4 + CHAIN_DEPTH * 8  # transport + flags + chain[4]

BANNER = "GENERATED by scripts/gen_abi_errors.py from abi/errors.yaml — DO NOT EDIT."
BANNER2 = (
    "Edit the IDL and regenerate; see docs/architecture/34-abi-idl-and-error-model.md."
)


def die(msg):
    print(f"gen_abi_errors: {msg}", file=sys.stderr)
    sys.exit(1)


class YamlUnavailable(RuntimeError):
    pass


def load_idl():
    try:
        import yaml
    except ImportError as exc:
        raise YamlUnavailable(
            "PyYAML is required to regenerate the ABI (pip install pyyaml); "
            "the checked-in generated files are used for normal builds."
        ) from exc
    with open(IDL_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


class Model:
    """Language-neutral view of the IDL, with ids/codes validated."""

    def __init__(self, idl):
        self.version = int(idl["abi_version"])
        self.transport = idl["transport"]
        self.domains = idl["domains"]

        seen = {}
        for t in self.transport:
            v = int(t["value"])
            if v in seen:
                die(f"transport value {v} reused by {seen[v]} and {t['name']}")
            seen[v] = t["name"]

        self.domain_upper_by_id = {}
        seen_ids = {}
        for name, d in self.domains.items():
            did = int(d["id"])
            if did in seen_ids:
                die(f"domain id {did} reused by '{seen_ids[did]}' and '{name}'")
            if did > 0xFFFF:
                die(f"domain id {did} ('{name}') exceeds u16")
            seen_ids[did] = name
            self.domain_upper_by_id[did] = name.upper()

        # packed entries: const suffix, domain upper, domain id, local, label, desc, packed int
        self.packed = []
        for dname, d in self.domains.items():
            did = int(d["id"])
            for i, code in enumerate(d.get("codes") or []):
                local = i + 1
                if local > 0xFFFF:
                    die(f"domain '{dname}' has too many codes")
                self.packed.append(
                    {
                        "const": f"WASMOS_ERR_{dname.upper()}_{code['name']}",
                        "domain_upper": dname.upper(),
                        "domain_id": did,
                        "local": local,
                        "label": f"{dname}.{code['name']}",
                        "desc": code.get("description", f"{dname}.{code['name']}"),
                        "packed": (did << 16) | local,
                    }
                )


# --------------------------------------------------------------------------- C


C_HELPERS = r"""static inline void wasmos_error_init(wasmos_error_t *e) {
    e->transport = WASMOS_OK;
    e->flags = 0;
    for (int i = 0; i < WASMOS_ERR_CHAIN_DEPTH; ++i) {
        e->chain[i].domain = 0;
        e->chain[i].code = 0;
        e->chain[i].origin = 0;
    }
}

static inline bool wasmos_error_ok(const wasmos_error_t *e) {
    return e->transport == WASMOS_OK && e->chain[0].domain == 0;
}

static inline wasmos_error_code_t wasmos_error_head(const wasmos_error_t *e) {
    return WASMOS_ERR_MAKE(e->chain[0].domain, e->chain[0].code);
}

static inline wasmos_error_code_t wasmos_error_root(const wasmos_error_t *e) {
    int i = 0;
    while (i + 1 < WASMOS_ERR_CHAIN_DEPTH && e->chain[i + 1].domain != 0) {
        ++i;
    }
    return WASMOS_ERR_MAKE(e->chain[i].domain, e->chain[i].code);
}

static inline wasmos_error_code_t wasmos_error_unwrap(const wasmos_error_t *e) {
    if (WASMOS_ERR_CHAIN_DEPTH < 2 || e->chain[1].domain == 0) {
        return WASMOS_ERR_NONE;
    }
    return WASMOS_ERR_MAKE(e->chain[1].domain, e->chain[1].code);
}

static inline bool wasmos_error_is(const wasmos_error_t *e, wasmos_error_code_t sentinel) {
    for (int i = 0; i < WASMOS_ERR_CHAIN_DEPTH; ++i) {
        if (e->chain[i].domain == 0) {
            break;
        }
        if (WASMOS_ERR_MAKE(e->chain[i].domain, e->chain[i].code) == sentinel) {
            return true;
        }
    }
    return false;
}

static inline bool wasmos_error_as(const wasmos_error_t *e, wasmos_error_domain_t dom,
                                   uint16_t *out_code) {
    for (int i = 0; i < WASMOS_ERR_CHAIN_DEPTH; ++i) {
        if (e->chain[i].domain == 0) {
            break;
        }
        if (e->chain[i].domain == dom) {
            if (out_code) {
                *out_code = e->chain[i].code;
            }
            return true;
        }
    }
    return false;
}

static inline void wasmos_error_set(wasmos_error_t *e, wasmos_error_domain_t dom,
                                    uint16_t code, uint32_t origin) {
    wasmos_error_init(e);
    e->chain[0].domain = dom;
    e->chain[0].code = code;
    e->chain[0].origin = origin;
}

static inline void wasmos_error_wrap(wasmos_error_t *e, wasmos_error_domain_t dom,
                                     uint16_t code, uint32_t origin) {
    int last = WASMOS_ERR_CHAIN_DEPTH - 1;
    if (e->chain[last].domain != 0) {
        for (int i = last - 1; i >= 1; --i) {
            e->chain[i] = e->chain[i - 1];
        }
        e->flags |= WASMOS_ERR_FLAG_TRUNCATED;
    } else {
        for (int i = last; i >= 1; --i) {
            e->chain[i] = e->chain[i - 1];
        }
    }
    e->chain[0].domain = dom;
    e->chain[0].code = code;
    e->chain[0].origin = origin;
}

static inline size_t wasmos_strerror_chain(const wasmos_error_t *e, char *buf, size_t n) {
    size_t w = 0;
    if (n == 0) {
        return 0;
    }
    for (int i = 0; i < WASMOS_ERR_CHAIN_DEPTH; ++i) {
        if (e->chain[i].domain == 0) {
            break;
        }
        if (i > 0) {
            const char *sep = " <- ";
            while (*sep && w + 1 < n) {
                buf[w++] = *sep++;
            }
        }
        wasmos_error_code_t packed = WASMOS_ERR_MAKE(e->chain[i].domain, e->chain[i].code);
        const char *dom = wasmos_error_domain_name(e->chain[i].domain);
        while (*dom && w + 1 < n) {
            buf[w++] = *dom++;
        }
        const char *colon = ": ";
        while (*colon && w + 1 < n) {
            buf[w++] = *colon++;
        }
        const char *desc = wasmos_strerror(packed);
        while (*desc && w + 1 < n) {
            buf[w++] = *desc++;
        }
    }
    if (w == 0) {
        const char *ok = "success";
        while (*ok && w + 1 < n) {
            buf[w++] = *ok++;
        }
    }
    buf[w] = '\0';
    return w;
}
"""


RUST_HELPERS = r"""
// Fixed error object (value ABI) + chain helpers (pure value ops). IPC framing
// lives in the libsys wrappers.
pub const WASMOS_ERR_CHAIN_DEPTH: usize = 4;
pub const WASMOS_ERR_FLAG_TRUNCATED: u32 = 1;

#[repr(C)]
#[derive(Copy, Clone)]
pub struct WasmosFrame {
    pub domain: u16,
    pub code: u16,
    pub origin: u32,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct WasmosError {
    pub transport: i32,
    pub flags: u32,
    pub chain: [WasmosFrame; WASMOS_ERR_CHAIN_DEPTH],
}

impl WasmosError {
    pub const fn new() -> Self {
        WasmosError {
            transport: WASMOS_OK,
            flags: 0,
            chain: [WasmosFrame { domain: 0, code: 0, origin: 0 }; WASMOS_ERR_CHAIN_DEPTH],
        }
    }
    pub fn is_ok(&self) -> bool {
        self.transport == WASMOS_OK && self.chain[0].domain == 0
    }
    pub fn head(&self) -> u32 {
        wasmos_err_make(self.chain[0].domain, self.chain[0].code)
    }
    pub fn root(&self) -> u32 {
        let mut i = 0;
        while i + 1 < WASMOS_ERR_CHAIN_DEPTH && self.chain[i + 1].domain != 0 {
            i += 1;
        }
        wasmos_err_make(self.chain[i].domain, self.chain[i].code)
    }
    pub fn unwrap_cause(&self) -> u32 {
        if WASMOS_ERR_CHAIN_DEPTH < 2 || self.chain[1].domain == 0 {
            return WASMOS_ERR_NONE;
        }
        wasmos_err_make(self.chain[1].domain, self.chain[1].code)
    }
    pub fn is(&self, sentinel: u32) -> bool {
        for f in &self.chain {
            if f.domain == 0 {
                break;
            }
            if wasmos_err_make(f.domain, f.code) == sentinel {
                return true;
            }
        }
        false
    }
    pub fn as_domain(&self, dom: u16) -> Option<u16> {
        for f in &self.chain {
            if f.domain == 0 {
                break;
            }
            if f.domain == dom {
                return Some(f.code);
            }
        }
        None
    }
    pub fn set(&mut self, dom: u16, code: u16, origin: u32) {
        *self = WasmosError::new();
        self.chain[0] = WasmosFrame { domain: dom, code, origin };
    }
    pub fn wrap(&mut self, dom: u16, code: u16, origin: u32) {
        let last = WASMOS_ERR_CHAIN_DEPTH - 1;
        let start = if self.chain[last].domain != 0 {
            self.flags |= WASMOS_ERR_FLAG_TRUNCATED;
            last - 1
        } else {
            last
        };
        let mut i = start;
        while i >= 1 {
            self.chain[i] = self.chain[i - 1];
            i -= 1;
        }
        self.chain[0] = WasmosFrame { domain: dom, code, origin };
    }
}
"""


GO_HELPERS = r"""
// Fixed error object (value ABI) + chain helpers (pure value ops). IPC framing
// lives in the libsys wrappers.
const WASMOS_ERR_CHAIN_DEPTH = 4
const WASMOS_ERR_FLAG_TRUNCATED uint32 = 1

type WasmosFrame struct {
    Domain uint16
    Code   uint16
    Origin uint32
}

type WasmosError struct {
    Transport int32
    Flags     uint32
    Chain     [WASMOS_ERR_CHAIN_DEPTH]WasmosFrame
}

func (e *WasmosError) Init() {
    e.Transport = WASMOS_OK
    e.Flags = 0
    for i := 0; i < WASMOS_ERR_CHAIN_DEPTH; i++ {
        e.Chain[i] = WasmosFrame{}
    }
}

func (e *WasmosError) IsOk() bool {
    return e.Transport == WASMOS_OK && e.Chain[0].Domain == 0
}

func (e *WasmosError) Head() uint32 {
    return WasmosErrMake(e.Chain[0].Domain, e.Chain[0].Code)
}

func (e *WasmosError) Root() uint32 {
    i := 0
    for i+1 < WASMOS_ERR_CHAIN_DEPTH && e.Chain[i+1].Domain != 0 {
        i++
    }
    return WasmosErrMake(e.Chain[i].Domain, e.Chain[i].Code)
}

func (e *WasmosError) UnwrapCause() uint32 {
    if WASMOS_ERR_CHAIN_DEPTH < 2 || e.Chain[1].Domain == 0 {
        return WASMOS_ERR_NONE
    }
    return WasmosErrMake(e.Chain[1].Domain, e.Chain[1].Code)
}

func (e *WasmosError) Is(sentinel uint32) bool {
    for i := 0; i < WASMOS_ERR_CHAIN_DEPTH; i++ {
        if e.Chain[i].Domain == 0 {
            break
        }
        if WasmosErrMake(e.Chain[i].Domain, e.Chain[i].Code) == sentinel {
            return true
        }
    }
    return false
}

func (e *WasmosError) As(dom uint16) (uint16, bool) {
    for i := 0; i < WASMOS_ERR_CHAIN_DEPTH; i++ {
        if e.Chain[i].Domain == 0 {
            break
        }
        if e.Chain[i].Domain == dom {
            return e.Chain[i].Code, true
        }
    }
    return 0, false
}

func (e *WasmosError) Set(dom uint16, code uint16, origin uint32) {
    e.Init()
    e.Chain[0] = WasmosFrame{Domain: dom, Code: code, Origin: origin}
}

func (e *WasmosError) Wrap(dom uint16, code uint16, origin uint32) {
    last := WASMOS_ERR_CHAIN_DEPTH - 1
    start := last
    if e.Chain[last].Domain != 0 {
        start = last - 1
        e.Flags |= WASMOS_ERR_FLAG_TRUNCATED
    }
    for i := start; i >= 1; i-- {
        e.Chain[i] = e.Chain[i-1]
    }
    e.Chain[0] = WasmosFrame{Domain: dom, Code: code, Origin: origin}
}
"""


ZIG_HELPERS = r"""
// Fixed error object (value ABI) + chain helpers (pure value ops). IPC framing
// lives in the libsys wrappers.
pub const WASMOS_ERR_CHAIN_DEPTH: usize = 4;
pub const WASMOS_ERR_FLAG_TRUNCATED: u32 = 1;

pub const Frame = extern struct {
    domain: u16,
    code: u16,
    origin: u32,
};

pub const Error = extern struct {
    transport: i32,
    flags: u32,
    chain: [WASMOS_ERR_CHAIN_DEPTH]Frame,

    pub fn init() Error {
        return .{
            .transport = WASMOS_OK,
            .flags = 0,
            .chain = [_]Frame{.{ .domain = 0, .code = 0, .origin = 0 }} ** WASMOS_ERR_CHAIN_DEPTH,
        };
    }
    pub fn isOk(self: *const Error) bool {
        return self.transport == WASMOS_OK and self.chain[0].domain == 0;
    }
    pub fn head(self: *const Error) u32 {
        return errMake(self.chain[0].domain, self.chain[0].code);
    }
    pub fn root(self: *const Error) u32 {
        var i: usize = 0;
        while (i + 1 < WASMOS_ERR_CHAIN_DEPTH and self.chain[i + 1].domain != 0) : (i += 1) {}
        return errMake(self.chain[i].domain, self.chain[i].code);
    }
    pub fn unwrapCause(self: *const Error) u32 {
        if (WASMOS_ERR_CHAIN_DEPTH < 2 or self.chain[1].domain == 0) return WASMOS_ERR_NONE;
        return errMake(self.chain[1].domain, self.chain[1].code);
    }
    pub fn is(self: *const Error, sentinel: u32) bool {
        var i: usize = 0;
        while (i < WASMOS_ERR_CHAIN_DEPTH) : (i += 1) {
            if (self.chain[i].domain == 0) break;
            if (errMake(self.chain[i].domain, self.chain[i].code) == sentinel) return true;
        }
        return false;
    }
    pub fn asDomain(self: *const Error, dom: u16) ?u16 {
        var i: usize = 0;
        while (i < WASMOS_ERR_CHAIN_DEPTH) : (i += 1) {
            if (self.chain[i].domain == 0) break;
            if (self.chain[i].domain == dom) return self.chain[i].code;
        }
        return null;
    }
    pub fn set(self: *Error, dom: u16, code: u16, origin: u32) void {
        self.* = Error.init();
        self.chain[0] = .{ .domain = dom, .code = code, .origin = origin };
    }
    pub fn wrap(self: *Error, dom: u16, code: u16, origin: u32) void {
        const last: usize = WASMOS_ERR_CHAIN_DEPTH - 1;
        var start: usize = last;
        if (self.chain[last].domain != 0) {
            start = last - 1;
            self.flags |= WASMOS_ERR_FLAG_TRUNCATED;
        }
        var i: usize = start;
        while (i >= 1) : (i -= 1) {
            self.chain[i] = self.chain[i - 1];
        }
        self.chain[0] = .{ .domain = dom, .code = code, .origin = origin };
    }

    comptime {
        if (@sizeOf(Frame) != 8) @compileError("Frame must be 8 bytes");
        if (@sizeOf(Error) != 40) @compileError("Error must be 40 bytes");
    }
};
"""


AS_HELPERS = r"""
// Fixed error object (value ABI) + chain helpers over a 40-byte block in linear
// memory (AS has no C-layout value struct). Layout: transport:i32@0, flags:u32@4,
// chain[4]@8; frame = domain:u16@0, code:u16@2, origin:u32@4. `e` is a pointer to
// the block. IPC framing lives in the libsys wrappers.
export const WASMOS_ERR_CHAIN_DEPTH: i32 = 4;
export const WASMOS_ERR_FLAG_TRUNCATED: u32 = 1;
export const WASMOS_ERR_SIZE: usize = 40;

function fBase(e: usize, i: i32): usize { return e + 8 + (<usize>i) * 8; }

export function errorInit(e: usize): void {
  for (let i: usize = 0; i < WASMOS_ERR_SIZE; i++) store<u8>(e + i, 0);
}
export function errorTransport(e: usize): i32 { return load<i32>(e); }
export function errorSetTransport(e: usize, s: i32): void { store<i32>(e, s); }
export function errorFlags(e: usize): u32 { return load<u32>(e + 4); }
export function errorIsOk(e: usize): bool {
  return load<i32>(e) == WASMOS_OK && load<u16>(e + 8) == 0;
}
export function errorHead(e: usize): u32 {
  const b = fBase(e, 0);
  return errMake(load<u16>(b), load<u16>(b + 2));
}
export function errorRoot(e: usize): u32 {
  let i: i32 = 0;
  while (i + 1 < WASMOS_ERR_CHAIN_DEPTH && load<u16>(fBase(e, i + 1)) != 0) i++;
  const b = fBase(e, i);
  return errMake(load<u16>(b), load<u16>(b + 2));
}
export function errorUnwrap(e: usize): u32 {
  if (WASMOS_ERR_CHAIN_DEPTH < 2 || load<u16>(fBase(e, 1)) == 0) return WASMOS_ERR_NONE;
  const b = fBase(e, 1);
  return errMake(load<u16>(b), load<u16>(b + 2));
}
export function errorIs(e: usize, sentinel: u32): bool {
  for (let i: i32 = 0; i < WASMOS_ERR_CHAIN_DEPTH; i++) {
    const b = fBase(e, i);
    if (load<u16>(b) == 0) break;
    if (errMake(load<u16>(b), load<u16>(b + 2)) == sentinel) return true;
  }
  return false;
}
// returns the code, or -1 when `dom` is not present in the chain
export function errorAs(e: usize, dom: u16): i32 {
  for (let i: i32 = 0; i < WASMOS_ERR_CHAIN_DEPTH; i++) {
    const b = fBase(e, i);
    if (load<u16>(b) == 0) break;
    if (load<u16>(b) == dom) return <i32>load<u16>(b + 2);
  }
  return -1;
}
export function errorSet(e: usize, dom: u16, code: u16, origin: u32): void {
  errorInit(e);
  const b = fBase(e, 0);
  store<u16>(b, dom);
  store<u16>(b + 2, code);
  store<u32>(b + 4, origin);
}
export function errorWrap(e: usize, dom: u16, code: u16, origin: u32): void {
  const last: i32 = WASMOS_ERR_CHAIN_DEPTH - 1;
  let start: i32 = last;
  if (load<u16>(fBase(e, last)) != 0) {
    start = last - 1;
    store<u32>(e + 4, load<u32>(e + 4) | WASMOS_ERR_FLAG_TRUNCATED);
  }
  for (let i: i32 = start; i >= 1; i--) {
    const d = fBase(e, i);
    const s = fBase(e, i - 1);
    store<u16>(d, load<u16>(s));
    store<u16>(d + 2, load<u16>(s + 2));
    store<u32>(d + 4, load<u32>(s + 4));
  }
  const b = fBase(e, 0);
  store<u16>(b, dom);
  store<u16>(b + 2, code);
  store<u32>(b + 4, origin);
}
"""


def emit_c(m):
    o = []
    w = o.append
    w("/*")
    w(f" * {BANNER}")
    w(f" * {BANNER2}")
    w(" */")
    w("#ifndef WASMOS_STATUS_H")
    w("#define WASMOS_STATUS_H")
    w("")
    w("#include <stdint.h>")
    w("#include <stdbool.h>")
    w("#include <stddef.h>")
    w("")
    w(f"#define WASMOS_ABI_ERRORS_VERSION {m.version}u")
    w("")
    w("/* Transport / kernel-IPC result axis: did the call mechanism work. */")
    w("typedef int32_t wasmos_status_t;")
    w("enum {")
    for t in m.transport:
        w(
            f"    WASMOS_{t['name']} = {int(t['value'])}, /* {esc(t.get('description',''))} */"
        )
    w("};")
    w("")
    w("/* Domain registry: stable ids, assigned only in the IDL. */")
    w("typedef uint16_t wasmos_error_domain_t;")
    w("enum {")
    for name, d in m.domains.items():
        w(
            f"    WASMOS_ERR_DOMAIN_{name.upper()} = {int(d['id'])}, /* {esc(d.get('description',''))} */"
        )
    w("};")
    w("")
    w("/* A domain error packs (domain << 16) | local_code into 32 bits. */")
    w("typedef uint32_t wasmos_error_code_t;")
    w("#define WASMOS_ERR_MAKE(dom, code) \\")
    w(
        "    ((wasmos_error_code_t)(((uint32_t)(dom) << 16) | ((uint32_t)(code) & 0xFFFFu)))"
    )
    w("#define WASMOS_ERR_DOMAIN_OF(x) ((wasmos_error_domain_t)((uint32_t)(x) >> 16))")
    w("#define WASMOS_ERR_CODE_OF(x)   ((uint16_t)((uint32_t)(x) & 0xFFFFu))")
    w("#define WASMOS_ERR_NONE ((wasmos_error_code_t)0u) /* success / empty frame */")
    w("")
    w("/* Packed domain error constants (use with wasmos_error_is / _as). */")
    w("enum {")
    for p in m.packed:
        w(
            f"    {p['const']} = WASMOS_ERR_MAKE(WASMOS_ERR_DOMAIN_{p['domain_upper']}, {p['local']}), /* {esc(p['desc'])} */"
        )
    w("};")
    w("")
    w(f"#define WASMOS_ERR_CHAIN_DEPTH {CHAIN_DEPTH}")
    w("#define WASMOS_ERR_FLAG_TRUNCATED (1u << 0)")
    w("")
    w(
        "/* One cause-chain frame: 8 bytes. domain==0 marks an empty/terminating slot. */"
    )
    w("typedef struct {")
    w("    uint16_t domain;")
    w("    uint16_t code;")
    w("    uint32_t origin; /* producing pid/context, 0 if none */")
    w("} wasmos_frame_t;")
    w("")
    w(
        "/* Fixed, always-carried error object (transport axis + reserved cause chain). */"
    )
    w("typedef struct {")
    w("    wasmos_status_t transport;")
    w("    uint32_t        flags;")
    w("    wasmos_frame_t  chain[WASMOS_ERR_CHAIN_DEPTH];")
    w("} wasmos_error_t;")
    w("")
    w('_Static_assert(sizeof(wasmos_frame_t) == 8, "wasmos_frame_t must be 8 bytes");')
    w(
        f'_Static_assert(sizeof(wasmos_error_t) == {ERROR_OBJ_BYTES}, "wasmos_error_t must be {ERROR_OBJ_BYTES} bytes");'
    )
    w("")
    w("static inline const char *wasmos_status_str(wasmos_status_t s) {")
    w("    switch (s) {")
    for t in m.transport:
        w(f"    case WASMOS_{t['name']}: return \"{t['name']}\";")
    w('    default: return "UNKNOWN_STATUS";')
    w("    }")
    w("}")
    w("")
    w("static inline const char *wasmos_error_domain_name(wasmos_error_domain_t d) {")
    w("    switch (d) {")
    for name, d in m.domains.items():
        w(f'    case WASMOS_ERR_DOMAIN_{name.upper()}: return "{name}";')
    w('    default: return "unknown";')
    w("    }")
    w("}")
    w("")
    w('/* Human-readable "domain.CODE" identity for a packed code. */')
    w("static inline const char *wasmos_error_code_name(wasmos_error_code_t c) {")
    w("    switch (c) {")
    w('    case WASMOS_ERR_NONE: return "none";')
    for p in m.packed:
        w(f"    case {p['const']}: return \"{p['label']}\";")
    w('    default: return "unknown";')
    w("    }")
    w("}")
    w("")
    w("/* Static description of a packed code. */")
    w("static inline const char *wasmos_strerror(wasmos_error_code_t c) {")
    w("    switch (c) {")
    w('    case WASMOS_ERR_NONE: return "success";')
    for p in m.packed:
        w(f"    case {p['const']}: return \"{esc(p['desc'])}\";")
    w('    default: return "unknown error";')
    w("    }")
    w("}")
    w("")
    w(C_HELPERS)
    w("#endif /* WASMOS_STATUS_H */")
    w("")
    return "\n".join(o)


# ------------------------------------------------------------------------- Rust


def emit_rust(m):
    o = []
    w = o.append
    w(f"// {BANNER}")
    w(f"// {BANNER2}")
    w("// Value ABI: constants, packed accessors, decode lookups, and the fixed")
    w("// error object + chain helpers (pure value ops). IPC framing lives in libsys.")
    w("")
    w(f"pub const WASMOS_ABI_ERRORS_VERSION: u32 = {m.version};")
    w("")
    w("// Transport / kernel-IPC result axis.")
    for t in m.transport:
        w(
            f"pub const WASMOS_{t['name']}: i32 = {int(t['value'])}; // {t.get('description','')}"
        )
    w("")
    w("// Domain registry (stable ids).")
    for name, d in m.domains.items():
        w(f"pub const WASMOS_ERR_DOMAIN_{name.upper()}: u16 = {int(d['id'])};")
    w("")
    w("pub const WASMOS_ERR_NONE: u32 = 0;")
    w("// Packed domain error constants: (domain << 16) | local_code.")
    for p in m.packed:
        w(f"pub const {p['const']}: u32 = 0x{p['packed']:08X}; // {p['desc']}")
    w("")
    w("#[inline]")
    w("pub const fn wasmos_err_make(dom: u16, code: u16) -> u32 {")
    w("    ((dom as u32) << 16) | (code as u32)")
    w("}")
    w("#[inline]")
    w("pub const fn wasmos_err_domain_of(x: u32) -> u16 {")
    w("    (x >> 16) as u16")
    w("}")
    w("#[inline]")
    w("pub const fn wasmos_err_code_of(x: u32) -> u16 {")
    w("    (x & 0xffff) as u16")
    w("}")
    w("")
    w("pub fn wasmos_status_str(s: i32) -> &'static str {")
    w("    match s {")
    for t in m.transport:
        w(f"        WASMOS_{t['name']} => \"{t['name']}\",")
    w('        _ => "UNKNOWN_STATUS",')
    w("    }")
    w("}")
    w("")
    w("pub fn wasmos_error_domain_name(d: u16) -> &'static str {")
    w("    match d {")
    for name, d in m.domains.items():
        w(f'        WASMOS_ERR_DOMAIN_{name.upper()} => "{name}",')
    w('        _ => "unknown",')
    w("    }")
    w("}")
    w("")
    w("pub fn wasmos_strerror(c: u32) -> &'static str {")
    w("    match c {")
    w('        WASMOS_ERR_NONE => "success",')
    for p in m.packed:
        w(f"        {p['const']} => \"{esc(p['desc'])}\",")
    w('        _ => "unknown error",')
    w("    }")
    w("}")
    w("")
    w(RUST_HELPERS)
    return "\n".join(o)


# --------------------------------------------------------------------------- Go


def emit_go(m):
    o = []
    w = o.append
    w(f"// {BANNER}")
    w(f"// {BANNER2}")
    w("// Value ABI: constants, packed accessors, decode lookups, and the fixed")
    w("// error object + chain helpers (pure value ops). IPC framing lives in libsys.")
    w("")
    w("package wasmosstatus")
    w("")
    w(f"const WasmosABIErrorsVersion uint32 = {m.version}")
    w("")
    w("// Transport / kernel-IPC result axis.")
    w("const (")
    for t in m.transport:
        w(
            f"\tWASMOS_{t['name']} int32 = {int(t['value'])} // {t.get('description','')}"
        )
    w(")")
    w("")
    w("// Domain registry (stable ids).")
    w("const (")
    for name, d in m.domains.items():
        w(f"\tWASMOS_ERR_DOMAIN_{name.upper()} uint16 = {int(d['id'])}")
    w(")")
    w("")
    w("const WASMOS_ERR_NONE uint32 = 0")
    w("")
    w("// Packed domain error constants: (domain << 16) | local_code.")
    w("const (")
    for p in m.packed:
        w(f"\t{p['const']} uint32 = 0x{p['packed']:08X} // {p['desc']}")
    w(")")
    w("")
    w("func WasmosErrMake(dom uint16, code uint16) uint32 {")
    w("\treturn (uint32(dom) << 16) | uint32(code)")
    w("}")
    w("func WasmosErrDomainOf(x uint32) uint16 { return uint16(x >> 16) }")
    w("func WasmosErrCodeOf(x uint32) uint16   { return uint16(x & 0xffff) }")
    w("")
    w("func WasmosStatusStr(s int32) string {")
    w("\tswitch s {")
    for t in m.transport:
        w(f"\tcase WASMOS_{t['name']}:")
        w(f'\t\treturn "{t["name"]}"')
    w("\tdefault:")
    w('\t\treturn "UNKNOWN_STATUS"')
    w("\t}")
    w("}")
    w("")
    w("func WasmosErrorDomainName(d uint16) string {")
    w("\tswitch d {")
    for name, d in m.domains.items():
        w(f"\tcase WASMOS_ERR_DOMAIN_{name.upper()}:")
        w(f'\t\treturn "{name}"')
    w("\tdefault:")
    w('\t\treturn "unknown"')
    w("\t}")
    w("}")
    w("")
    w("func WasmosStrerror(c uint32) string {")
    w("\tswitch c {")
    w("\tcase WASMOS_ERR_NONE:")
    w('\t\treturn "success"')
    for p in m.packed:
        w(f"\tcase {p['const']}:")
        w(f'\t\treturn "{esc(p["desc"])}"')
    w("\tdefault:")
    w('\t\treturn "unknown error"')
    w("\t}")
    w("}")
    w("")
    w(GO_HELPERS)
    return "\n".join(o)


# -------------------------------------------------------------------------- Zig


def emit_zig(m):
    o = []
    w = o.append
    w(f"// {BANNER}")
    w(f"// {BANNER2}")
    w("// Value ABI: constants, packed accessors, decode lookups, and the fixed")
    w("// error object + chain helpers (pure value ops). IPC framing lives in libsys.")
    w("")
    w(f"pub const WASMOS_ABI_ERRORS_VERSION: u32 = {m.version};")
    w("")
    w("// Transport / kernel-IPC result axis.")
    for t in m.transport:
        w(
            f"pub const WASMOS_{t['name']}: i32 = {int(t['value'])}; // {t.get('description','')}"
        )
    w("")
    w("// Domain registry (stable ids).")
    for name, d in m.domains.items():
        w(f"pub const WASMOS_ERR_DOMAIN_{name.upper()}: u16 = {int(d['id'])};")
    w("")
    w("pub const WASMOS_ERR_NONE: u32 = 0;")
    w("// Packed domain error constants: (domain << 16) | local_code.")
    for p in m.packed:
        w(f"pub const {p['const']}: u32 = 0x{p['packed']:08X}; // {p['desc']}")
    w("")
    w("pub fn errMake(dom: u16, code: u16) u32 {")
    w("    return (@as(u32, dom) << 16) | @as(u32, code);")
    w("}")
    w("pub fn errDomainOf(x: u32) u16 {")
    w("    return @intCast(x >> 16);")
    w("}")
    w("pub fn errCodeOf(x: u32) u16 {")
    w("    return @intCast(x & 0xffff);")
    w("}")
    w("")
    w("pub fn statusStr(s: i32) []const u8 {")
    w("    return switch (s) {")
    for t in m.transport:
        w(f'        WASMOS_{t["name"]} => "{t["name"]}",')
    w('        else => "UNKNOWN_STATUS",')
    w("    };")
    w("}")
    w("")
    w("pub fn errorDomainName(d: u16) []const u8 {")
    w("    return switch (d) {")
    for name, d in m.domains.items():
        w(f'        WASMOS_ERR_DOMAIN_{name.upper()} => "{name}",')
    w('        else => "unknown",')
    w("    };")
    w("}")
    w("")
    w("pub fn strerror(c: u32) []const u8 {")
    w("    return switch (c) {")
    w('        WASMOS_ERR_NONE => "success",')
    for p in m.packed:
        w(f'        {p["const"]} => "{esc(p["desc"])}",')
    w('        else => "unknown error",')
    w("    };")
    w("}")
    w("")
    w(ZIG_HELPERS)
    return "\n".join(o)


# ---------------------------------------------------------------- AssemblyScript


def emit_as(m):
    o = []
    w = o.append
    w(f"// {BANNER}")
    w(f"// {BANNER2}")
    w("// Value ABI: constants, packed accessors, decode lookups, and the fixed")
    w("// error object + chain helpers (pointer-based over the 40-byte block).")
    w("")
    w(f"export const WASMOS_ABI_ERRORS_VERSION: u32 = {m.version};")
    w("")
    w("// Transport / kernel-IPC result axis.")
    for t in m.transport:
        w(
            f"export const WASMOS_{t['name']}: i32 = {int(t['value'])}; // {t.get('description','')}"
        )
    w("")
    w("// Domain registry (stable ids).")
    for name, d in m.domains.items():
        w(f"export const WASMOS_ERR_DOMAIN_{name.upper()}: u16 = {int(d['id'])};")
    w("")
    w("export const WASMOS_ERR_NONE: u32 = 0;")
    w("// Packed domain error constants: (domain << 16) | local_code.")
    for p in m.packed:
        w(f"export const {p['const']}: u32 = 0x{p['packed']:08X}; // {p['desc']}")
    w("")
    w("export function errMake(dom: u16, code: u16): u32 {")
    w("  return ((<u32>dom) << 16) | (<u32>code);")
    w("}")
    w("export function errDomainOf(x: u32): u16 { return <u16>(x >> 16); }")
    w("export function errCodeOf(x: u32): u16 { return <u16>(x & 0xffff); }")
    w("")
    w("export function statusStr(s: i32): string {")
    w("  switch (s) {")
    for t in m.transport:
        w(f'    case WASMOS_{t["name"]}: return "{t["name"]}";')
    w('    default: return "UNKNOWN_STATUS";')
    w("  }")
    w("}")
    w("")
    w("export function errorDomainName(d: u16): string {")
    w("  switch (d) {")
    for name, d in m.domains.items():
        w(f'    case WASMOS_ERR_DOMAIN_{name.upper()}: return "{name}";')
    w('    default: return "unknown";')
    w("  }")
    w("}")
    w("")
    w("export function strerror(c: u32): string {")
    w("  switch (c) {")
    w('    case WASMOS_ERR_NONE: return "success";')
    for p in m.packed:
        w(f'    case {p["const"]}: return "{esc(p["desc"])}";')
    w('    default: return "unknown error";')
    w("  }")
    w("}")
    w("")
    w(AS_HELPERS)
    return "\n".join(o)


def emit_docs(m):
    """Markdown error/status reference: the transport axis + every domain's codes."""
    o = [
        "<!-- GENERATED by scripts/gen_abi_errors.py from abi/errors.yaml — DO NOT EDIT. -->",
        "# WASMOS Error / Status Codes",
        "",
        "Two axes: **transport** (`wasmos_status_t`, the global call-mechanism result)",
        "and **domains** (namespaced operation errors, packed as `(domain << 16) | code`).",
        "",
        "## Transport (`wasmos_status_t`)",
        "",
        "| Name | Value | Description |",
        "|---|---|---|",
    ]
    for t in m.transport:
        desc = str(t.get("description", "")).replace("|", "\\|")
        o.append(f"| `WASMOS_{t['name']}` | {int(t['value'])} | {desc} |")
    o.append("")
    o.append("## Domains")
    o.append("")
    for dname, d in m.domains.items():
        did = int(d["id"])
        ddesc = str(d.get("description", "")).replace("|", "\\|")
        o.append(f"### `{dname}` (domain {did}) — {ddesc}")
        o.append("")
        codes = [p for p in m.packed if p["domain_id"] == did]
        if not codes:
            o.append("*(no codes)*")
            o.append("")
            continue
        o.append("| Code | Packed | Description |")
        o.append("|---|---|---|")
        for p in codes:
            desc = str(p["desc"]).replace("|", "\\|")
            o.append(f"| `{p['const']}` | 0x{p['packed']:08X} | {desc} |")
        o.append("")
    return "\n".join(o)


EMITTERS = {
    "c": ("c/wasmos_status.h", emit_c),
    "rust": ("rust/wasmos_status.rs", emit_rust),
    "go": ("go/wasmos_status.go", emit_go),
    "zig": ("zig/wasmos_status.zig", emit_zig),
    "assemblyscript": ("assemblyscript/wasmos_status.ts", emit_as),
}

# Always emitted on a full run (not a per-language --lang choice).
EXTRA_OUTPUTS = [("docs/errors.md", emit_docs)]


def main():
    ap = argparse.ArgumentParser(description="Generate the wasmos error/status ABI.")
    ap.add_argument(
        "--check",
        action="store_true",
        help="fail if any on-disk file differs from the IDL",
    )
    ap.add_argument("--lang", choices=sorted(EMITTERS), help="restrict to one language")
    args = ap.parse_args()

    try:
        model = Model(load_idl())
    except YamlUnavailable as exc:
        if args.check:
            print(f"gen_abi_errors: skipping check ({exc})", file=sys.stderr)
            return
        die(str(exc))

    langs = [args.lang] if args.lang else list(EMITTERS)
    outputs = [EMITTERS[lang] for lang in langs]
    if not args.lang:
        outputs += EXTRA_OUTPUTS  # docs/errors.md on a full run
    stale = False
    for rel, emit in outputs:
        text = emit(model)
        path = os.path.join(GEN_ROOT, rel)
        if args.check:
            try:
                with open(path, "r", encoding="utf-8") as f:
                    current = f.read()
            except FileNotFoundError:
                current = None
            if current != text:
                print(
                    f"gen_abi_errors: {os.path.relpath(path, REPO_ROOT)} is stale",
                    file=sys.stderr,
                )
                stale = True
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(text)
            print(f"gen_abi_errors: wrote {os.path.relpath(path, REPO_ROOT)}")

    if args.check:
        if stale:
            print(
                "gen_abi_errors: run scripts/gen_abi_errors.py to regenerate",
                file=sys.stderr,
            )
            sys.exit(2)
        print("gen_abi_errors: all generated ABI files are up to date")


if __name__ == "__main__":
    main()
