#!/usr/bin/env python3
"""Generate the WASM/IPC opcode ABI from abi/opcodes.yaml.

Opcodes are the POSITIVE `type` field of ipc_message_t, owned per subsystem in
`src/drivers/include/wasmos_driver_abi.h`. This is the ABI-header core: negative
`*_ERR_*` codes live in abi/errors.yaml, and flags/descriptor structs stay
hand-written in the header.

Generates (into abi/generated/c/):
  - wasmos_opcodes.h   per-subsystem opcode enums (reproducing the header) +
                       a best-effort wasmos_opcode_name(type) diagnostic lookup

and (into abi/generated/docs/):
  - opcodes.md         per-subsystem reference tables for the docs

See docs/architecture/34-abi-idl-and-error-model.md.

Opcode values are NOT globally unique — they are endpoint-scoped, so the same
value can appear in two subsystems (e.g. 0x223 is both a proc_broker and a
service_registry request). C enums do not require cross-enum value uniqueness,
so the per-subsystem enums reproduce that faithfully; the global name lookup is
best-effort (first subsystem in id order wins; shadowed symbols are listed in a
comment).

Usage:
    gen_abi_opcodes.py [--check] [--verify-source]
      (no args)        regenerate all generated opcode files
      --check          fail (exit 2) if any on-disk file differs from the IDL
      --verify-source  fail (exit 3) if the IDL does not reproduce the live
                       opcode enums in wasmos_driver_abi.h (symbol -> value)
"""

import argparse
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IDL_PATH = os.path.join(REPO_ROOT, "abi", "opcodes.yaml")
GEN_C_DIR = os.path.join(REPO_ROOT, "abi", "generated", "c")
GEN_DOCS_DIR = os.path.join(REPO_ROOT, "abi", "generated", "docs")
OPCODES_H = os.path.join(GEN_C_DIR, "wasmos_opcodes.h")
OPCODES_MD = os.path.join(GEN_DOCS_DIR, "opcodes.md")

GEN_ROOT = os.path.join(REPO_ROOT, "abi", "generated")
RUST_OUT = os.path.join(GEN_ROOT, "rust", "wasmos_opcodes.rs")
GO_OUT = os.path.join(GEN_ROOT, "go", "wasmos_opcodes.go")
ZIG_OUT = os.path.join(GEN_ROOT, "zig", "wasmos_opcodes.zig")
AS_OUT = os.path.join(GEN_ROOT, "assemblyscript", "wasmos_opcodes.ts")

DRIVER_ABI_H = os.path.join(
    REPO_ROOT, "src", "drivers", "include", "wasmos_driver_abi.h"
)


def die(msg, code=1):
    print(f"gen_abi_opcodes: {msg}", file=sys.stderr)
    sys.exit(code)


class YamlUnavailable(RuntimeError):
    pass


def load_idl():
    try:
        import yaml
    except ImportError as exc:
        raise YamlUnavailable(
            "PyYAML is required to regenerate the opcode ABI (pip install pyyaml); "
            "the checked-in generated files are used for normal builds."
        ) from exc
    with open(IDL_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


class Model:
    def __init__(self, idl):
        self.version = int(idl["abi_version"])
        self.subsystems = idl["subsystems"]

        seen_id, seen_sym = {}, {}
        for s in self.subsystems:
            sid = int(s["id"])
            if sid in seen_id:
                die(f"duplicate subsystem id {sid}: {seen_id[sid]} and {s['name']}")
            seen_id[sid] = s["name"]
            vals = {}
            for o in s["opcodes"]:
                v = int(o["value"])
                if v in vals:
                    die(
                        f"{s['name']}: duplicate value {hex(v)}: {vals[v]} and {o['symbol']}"
                    )
                vals[v] = o["symbol"]
                if o["symbol"] in seen_sym:
                    die(f"duplicate opcode symbol {o['symbol']}")
                seen_sym[o["symbol"]] = v
        # subsystem ids dense 0..N-1
        n = len(self.subsystems)
        missing = [i for i in range(n) if i not in seen_id]
        if missing:
            die(f"subsystem id space has gaps: missing {missing}")
        self.by_id = [
            next(s for s in self.subsystems if int(s["id"]) == i) for i in range(n)
        ]
        self.symbols = seen_sym

    @staticmethod
    def value(o):
        return int(o["value"])


BANNER = [
    "/*",
    " * GENERATED by scripts/gen_abi_opcodes.py from abi/opcodes.yaml — DO NOT EDIT.",
    " * See docs/architecture/34-abi-idl-and-error-model.md.",
    " */",
]


def _doc_block(text, indent):
    if not text:
        return []
    lines = text.rstrip("\n").split("\n") if isinstance(text, str) else list(text)
    if len(lines) == 1:
        return [f"{indent}/* {lines[0]} */"]
    out = [f"{indent}/* {lines[0]}"]
    out += [f"{indent} * {ln}".rstrip() for ln in lines[1:]]
    out.append(f"{indent} */")
    return out


def emit_opcodes_h(m):
    o = list(BANNER)
    w = o.append
    w("#ifndef WASMOS_GENERATED_OPCODES_H")
    w("#define WASMOS_GENERATED_OPCODES_H")
    w("")
    w("#include <stdint.h>")
    w("")
    w("/* Per-subsystem IPC opcode enums (positive ipc_message_t `type` values).")
    w(" * Values are endpoint-scoped and may repeat across subsystems. */")
    for s in m.by_id:
        lo = min(m.value(op) for op in s["opcodes"])
        hi = max(m.value(op) for op in s["opcodes"])
        w("")
        w(f"/* {s['name']} (0x{lo:X}..0x{hi:X}) */")
        w("enum {")
        for op in s["opcodes"]:
            o.extend(_doc_block(op.get("doc"), "    "))
            w(f"    {op['symbol']} = 0x{m.value(op):X},")
        w("};")
    # best-effort global name lookup (first subsystem in id order wins on a
    # value collision; shadowed symbols are listed for the reader).
    seen = {}
    shadowed = []
    for s in m.by_id:
        for op in s["opcodes"]:
            v = m.value(op)
            if v in seen:
                shadowed.append((op["symbol"], v, seen[v]))
            else:
                seen[v] = op["symbol"]
    w("")
    w("/* Best-effort opcode -> symbol name for diagnostics/logging. Opcode values")
    w(" * are endpoint-scoped, so on a cross-subsystem value collision the first")
    w(" * subsystem (in id order) wins here:")
    for sym, v, winner in shadowed:
        w(f" *   0x{v:X} {sym} shadowed by {winner}")
    if not shadowed:
        w(" *   (no value collisions)")
    w(" * Callers that know the peer subsystem should prefer the enum directly. */")
    w("static inline const char* wasmos_opcode_name(uint32_t type) {")
    w("    switch (type) {")
    for v in sorted(seen):
        w(f'    case 0x{v:X}: return "{seen[v]}";')
    w('    default: return "UNKNOWN";')
    w("    }")
    w("}")
    w("")
    w("#endif /* WASMOS_GENERATED_OPCODES_H */")
    w("")
    return "\n".join(o)


def emit_opcodes_md(m):
    o = [
        "<!-- GENERATED by scripts/gen_abi_opcodes.py from abi/opcodes.yaml — DO NOT EDIT. -->",
        "# WASMOS IPC Opcodes",
        "",
        "Positive `ipc_message_t.type` values, owned per subsystem. Values are",
        "endpoint-scoped and may repeat across subsystems.",
        "",
    ]
    for s in m.by_id:
        lo = min(m.value(op) for op in s["opcodes"])
        hi = max(m.value(op) for op in s["opcodes"])
        o.append(f"## {s['name']} (0x{lo:X}–0x{hi:X})")
        o.append("")
        o.append("| Opcode | Value | Kind | Description |")
        o.append("|---|---|---|---|")
        for op in s["opcodes"]:
            doc = op.get("doc") or ""
            if not isinstance(doc, str):
                doc = " ".join(doc)
            doc = doc.replace("\n", " ").replace("|", "\\|")
            o.append(
                f"| `{op['symbol']}` | 0x{m.value(op):X} | {op.get('kind','')} | {doc} |"
            )
        o.append("")
    return "\n".join(o)


_GEN = "GENERATED by scripts/gen_abi_opcodes.py from abi/opcodes.yaml — DO NOT EDIT."
_REF = "See docs/architecture/34-abi-idl-and-error-model.md."


def _doc_lines(text, prefix):
    if not text:
        return []
    lines = text.rstrip("\n").split("\n") if isinstance(text, str) else list(text)
    return [f"{prefix} {ln}".rstrip() for ln in lines]


def _lang(m, hdr, subsystem_fmt, const_fmt, doc_prefix):
    """Shared per-language emitter: opcode constants grouped by subsystem, each
    keeping the exact C symbol name (greppable/consistent across languages)."""
    o = [f"// {_GEN}", f"// {_REF}", ""] + list(hdr)
    for s in m.by_id:
        lo = min(m.value(op) for op in s["opcodes"])
        hi = max(m.value(op) for op in s["opcodes"])
        o.append("")
        o.append(subsystem_fmt(s["name"], lo, hi))
        for op in s["opcodes"]:
            o.extend(_doc_lines(op.get("doc"), doc_prefix))
            o.append(const_fmt(op["symbol"], m.value(op)))
    o.append("")
    return "\n".join(o)


def emit_rust(m):
    return _lang(
        m,
        ["#![allow(dead_code)]"],
        lambda n, lo, hi: f"// {n} (0x{lo:X}..0x{hi:X})",
        lambda sym, v: f"pub const {sym}: i32 = 0x{v:X};",
        "///",
    )


def emit_go(m):
    return _lang(
        m,
        ["package wasmos"],
        lambda n, lo, hi: f"// {n} (0x{lo:X}..0x{hi:X})",
        lambda sym, v: f"const {sym} int32 = 0x{v:X}",
        "//",
    )


def emit_zig(m):
    return _lang(
        m,
        [],
        lambda n, lo, hi: f"// {n} (0x{lo:X}..0x{hi:X})",
        lambda sym, v: f"pub const {sym}: i32 = 0x{v:X};",
        "///",
    )


def emit_as(m):
    return _lang(
        m,
        [],
        lambda n, lo, hi: f"// {n} (0x{lo:X}..0x{hi:X})",
        lambda sym, v: f"export const {sym}: i32 = 0x{v:X};",
        "//",
    )


OUTPUTS = [
    (OPCODES_H, emit_opcodes_h),
    (OPCODES_MD, emit_opcodes_md),
    (RUST_OUT, emit_rust),
    (GO_OUT, emit_go),
    (ZIG_OUT, emit_zig),
    (AS_OUT, emit_as),
]


def _read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def verify_source(m):
    """Assert the live wasmos_driver_abi.h opcode enums (positive values in
    0x100..0xCFF) reproduce the IDL symbol->value map exactly. Self-skips once
    the header is swapped to #include the generated enums."""
    text = _read(DRIVER_ABI_H)
    if "wasmos_opcodes.h" in text:
        print(
            "gen_abi_opcodes: header already swapped to the generated enums; --check guards it"
        )
        return
    src = {
        sym: int(val, 16)
        for sym, val in re.findall(r"([A-Z][A-Z0-9_]+)\s*=\s*(0x[0-9A-Fa-f]+)", text)
        if 0x100 <= int(val, 16) <= 0xCFF
    }
    problems = []
    if set(src) != set(m.symbols):
        problems.append(
            f"opcode symbol set differs: only-src={sorted(set(src) - set(m.symbols))} "
            f"only-idl={sorted(set(m.symbols) - set(src))}"
        )
    for sym in set(src) & set(m.symbols):
        if src[sym] != m.symbols[sym]:
            problems.append(
                f"value mismatch {sym}: src=0x{src[sym]:X} idl=0x{m.symbols[sym]:X}"
            )
    if problems:
        for p in problems:
            print(f"gen_abi_opcodes: {p}", file=sys.stderr)
        die(
            "IDL does not match the live opcode enums — reconcile before generating",
            code=3,
        )
    print(
        f"gen_abi_opcodes: IDL verified against wasmos_driver_abi.h "
        f"({len(m.symbols)} opcodes across {len(m.subsystems)} subsystems)"
    )


def main():
    ap = argparse.ArgumentParser(description="Generate the WASM/IPC opcode ABI.")
    ap.add_argument(
        "--check", action="store_true", help="fail if any generated file is stale"
    )
    ap.add_argument(
        "--verify-source", action="store_true", help="fail if the IDL ≠ the live enums"
    )
    args = ap.parse_args()

    try:
        model = Model(load_idl())
    except YamlUnavailable as exc:
        if args.check or args.verify_source:
            print(f"gen_abi_opcodes: skipping ({exc})", file=sys.stderr)
            return
        die(str(exc))

    if args.verify_source:
        verify_source(model)
        return

    if args.check:
        stale = False
        for path, emit in OUTPUTS:
            want = emit(model)
            have = _read(path) if os.path.exists(path) else None
            if have != want:
                print(
                    f"gen_abi_opcodes: {os.path.relpath(path, REPO_ROOT)} is stale",
                    file=sys.stderr,
                )
                stale = True
        if stale:
            die("run scripts/gen_abi_opcodes.py to regenerate", code=2)
        print("gen_abi_opcodes: all generated opcode files are up to date")
        return

    for path, emit in OUTPUTS:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(emit(model))
        print(f"gen_abi_opcodes: wrote {os.path.relpath(path, REPO_ROOT)}")


if __name__ == "__main__":
    main()
