#!/usr/bin/env python3
"""Generate the WASM host-call ABI from abi/hostcalls.yaml.

This increment generates the kernel HC_* id enum
(abi/generated/c/wasmos_hostcall_ids.h) and can verify it against the live
hand-written enum in src/kernel/include/warp_ring3.h. Later increments add the
WARP WASMOS_SYMBOLS tables, the wasm3 link table + m3 sig strings, the ring-3
dispatch, the AOT symbol table, and the per-language client stubs.

See docs/architecture/34-abi-idl-and-error-model.md.

ID guarantees enforced by the Model (see abi/hostcalls.yaml header):
  - every hostcall has a unique `id`;
  - the id space is dense (0..N-1) — a gap aborts generation, a retired slot
    must be an explicit `reserved: true` entry;
  - emission is ordered by id (== ring-3 syscall number == AOT rebind index).

Usage:
    gen_abi_hostcalls.py [--check] [--verify-source]
      (no args)        regenerate abi/generated/c/wasmos_hostcall_ids.h
      --check          fail (exit 2) if the on-disk file differs from the IDL
      --verify-source  fail (exit 3) if the IDL's (symbol, id) set does not
                       match src/kernel/include/warp_ring3.h (semantic diff)
"""

import argparse
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IDL_PATH = os.path.join(REPO_ROOT, "abi", "hostcalls.yaml")
IDS_OUT = os.path.join(REPO_ROOT, "abi", "generated", "c", "wasmos_hostcall_ids.h")
WARP_RING3_H = os.path.join(REPO_ROOT, "src", "kernel", "include", "warp_ring3.h")

MODULE_PREFIX = {"wasmos": "", "env": "ENV_", "wasi_snapshot_preview1": "WASI_"}


def die(msg, code=1):
    print(f"gen_abi_hostcalls: {msg}", file=sys.stderr)
    sys.exit(code)


class YamlUnavailable(RuntimeError):
    pass


def load_idl():
    try:
        import yaml
    except ImportError as exc:
        raise YamlUnavailable(
            "PyYAML is required to regenerate the host-call ABI (pip install pyyaml); "
            "the checked-in generated files are used for normal builds."
        ) from exc
    with open(IDL_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def hc_symbol(entry):
    """HC_* enum symbol: HC_ + module-prefix + UPPER(name)."""
    module = entry.get("module", "wasmos")
    if module not in MODULE_PREFIX:
        die(f"unknown module '{module}' for host call '{entry.get('name')}'")
    if entry.get("reserved"):
        return f"HC_RESERVED_{entry['id']}"
    return "HC_" + MODULE_PREFIX[module] + entry["name"].upper()


class Model:
    def __init__(self, idl):
        self.version = int(idl["abi_version"])
        self.hostcalls = idl["hostcalls"]

        # --- id validation: unique, dense 0..N-1 ----------------------------
        by_id = {}
        for e in self.hostcalls:
            if "id" not in e:
                die(f"host call '{e.get('name')}' has no id")
            i = int(e["id"])
            if i in by_id:
                die(f"duplicate id {i}: '{by_id[i].get('name')}' and '{e.get('name')}'")
            by_id[i] = e
        n = len(self.hostcalls)
        missing = [i for i in range(n) if i not in by_id]
        if missing:
            die(
                f"id space has gaps (not dense 0..{n - 1}): missing {missing}. "
                f"Retired slots must be explicit `reserved: true` entries."
            )

        # emission order == id order
        self.ordered = [by_id[i] for i in range(n)]
        self.count = n

        # --- HC symbol uniqueness (names may repeat across modules) ---------
        syms = {}
        for e in self.ordered:
            s = hc_symbol(e)
            if s in syms:
                die(f"duplicate HC symbol {s} (ids {syms[s]} and {e['id']})")
            syms[s] = e["id"]
        self.symbols = syms  # {HC_SYMBOL: id}

    def alias_comment(self, e):
        if "alias_of" in e:
            return f" /* alias: {e['name']} → warp_{e['alias_of']} */"
        if e.get("reserved"):
            return " /* reserved (retired host call; slot kept for id stability) */"
        return ""


def emit_hostcall_ids(m):
    o = []
    w = o.append
    w("/*")
    w(
        " * GENERATED by scripts/gen_abi_hostcalls.py from abi/hostcalls.yaml — DO NOT EDIT."
    )
    w(" * See docs/architecture/34-abi-idl-and-error-model.md.")
    w(" */")
    w("#ifndef WASMOS_HOSTCALL_IDS_H")
    w("#define WASMOS_HOSTCALL_IDS_H")
    w("")
    w("/* Ordered hostcall IDs — must match WASMOS_SYMBOLS expansion order. */")
    w("typedef enum {")
    for e in m.ordered:
        w(f"    {hc_symbol(e)} = {e['id']},{m.alias_comment(e)}")
    w(f"    HC_COUNT = {m.count},")
    w("} warp_hostcall_id_t;")
    w("")
    w("#endif /* WASMOS_HOSTCALL_IDS_H */")
    w("")
    return "\n".join(o)


def parse_source_enum():
    """Extract {HC_SYMBOL: id} from the hand-written enum in warp_ring3.h."""
    with open(WARP_RING3_H, "r", encoding="utf-8") as f:
        text = f.read()
    pairs = {}
    for sym, val in re.findall(r"\b(HC_[A-Z0-9_]+)\s*=\s*(\d+)", text):
        pairs[sym] = int(val)
    return pairs


def verify_source(m):
    src = parse_source_enum()
    src_count = src.pop("HC_COUNT", None)
    idl = dict(m.symbols)
    ok = True
    only_src = sorted(set(src) - set(idl))
    only_idl = sorted(set(idl) - set(src))
    if only_src:
        print(
            f"gen_abi_hostcalls: in warp_ring3.h but not the IDL: {only_src}",
            file=sys.stderr,
        )
        ok = False
    if only_idl:
        print(
            f"gen_abi_hostcalls: in the IDL but not warp_ring3.h: {only_idl}",
            file=sys.stderr,
        )
        ok = False
    for sym in sorted(set(src) & set(idl)):
        if src[sym] != idl[sym]:
            print(
                f"gen_abi_hostcalls: id mismatch {sym}: warp_ring3.h={src[sym]} IDL={idl[sym]}",
                file=sys.stderr,
            )
            ok = False
    if src_count is not None and src_count != m.count:
        print(
            f"gen_abi_hostcalls: HC_COUNT mismatch: warp_ring3.h={src_count} IDL={m.count}",
            file=sys.stderr,
        )
        ok = False
    if not ok:
        die("IDL does not match warp_ring3.h — reconcile before generating", code=3)
    print(
        f"gen_abi_hostcalls: IDL matches warp_ring3.h ({m.count} host calls, ids 0..{m.count - 1})"
    )


def main():
    ap = argparse.ArgumentParser(description="Generate the WASM host-call ABI.")
    ap.add_argument(
        "--check",
        action="store_true",
        help="fail if the on-disk generated file differs from the IDL",
    )
    ap.add_argument(
        "--verify-source",
        action="store_true",
        help="fail if the IDL's (symbol, id) set differs from warp_ring3.h",
    )
    args = ap.parse_args()

    try:
        model = Model(load_idl())
    except YamlUnavailable as exc:
        if args.check or args.verify_source:
            print(f"gen_abi_hostcalls: skipping ({exc})", file=sys.stderr)
            return
        die(str(exc))

    if args.verify_source:
        verify_source(model)
        return

    header = emit_hostcall_ids(model)
    if args.check:
        try:
            with open(IDS_OUT, "r", encoding="utf-8") as f:
                current = f.read()
        except FileNotFoundError:
            current = None
        if current != header:
            die(
                f"{os.path.relpath(IDS_OUT, REPO_ROOT)} is stale; run scripts/gen_abi_hostcalls.py",
                code=2,
            )
        print(f"gen_abi_hostcalls: {os.path.relpath(IDS_OUT, REPO_ROOT)} is up to date")
        return

    os.makedirs(os.path.dirname(IDS_OUT), exist_ok=True)
    with open(IDS_OUT, "w", encoding="utf-8") as f:
        f.write(header)
    print(
        f"gen_abi_hostcalls: wrote {os.path.relpath(IDS_OUT, REPO_ROOT)} "
        f"({model.count} host calls)"
    )


if __name__ == "__main__":
    main()
