#!/usr/bin/env python3
"""Generate the wasmos error/status ABI from abi/errors.yaml.

Single source of truth -> generated C header (later increments add per-language
constant tables). See docs/architecture/34-abi-idl-and-error-model.md.

Usage:
    gen_abi_errors.py [--check] [--out PATH]

    (no args)   regenerate abi/generated/wasmos_status.h in place
    --out PATH  write the header to PATH instead
    --check     regenerate into memory and fail (exit 2) if the on-disk header
                differs; used by the `quality` re-gen guard so generated output
                can never silently drift from the IDL
"""

import argparse
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IDL_PATH = os.path.join(REPO_ROOT, "abi", "errors.yaml")
DEFAULT_OUT = os.path.join(REPO_ROOT, "abi", "generated", "wasmos_status.h")

CHAIN_DEPTH = 4
ERROR_OBJ_BYTES = 4 + 4 + CHAIN_DEPTH * 8  # transport + flags + chain[4]


def die(msg):
    print(f"gen_abi_errors: {msg}", file=sys.stderr)
    sys.exit(1)


class YamlUnavailable(RuntimeError):
    pass


def load_idl():
    try:
        import yaml
    except ImportError as exc:
        raise YamlUnavailable(
            "PyYAML is required to regenerate the ABI (pip install pyyaml); "
            "the checked-in generated header is used for normal builds."
        ) from exc
    with open(IDL_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def c_str(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def build(idl):
    """Return (header_text). Validates ids/codes are collision-free."""
    version = int(idl["abi_version"])
    transport = idl["transport"]
    domains = idl["domains"]

    # --- validation: unique transport values, unique domain ids -------------
    seen_vals = {}
    for t in transport:
        v = int(t["value"])
        if v in seen_vals:
            die(f"transport value {v} used by both {seen_vals[v]} and {t['name']}")
        seen_vals[v] = t["name"]

    seen_ids = {}
    for name, d in domains.items():
        did = int(d["id"])
        if did in seen_ids:
            die(f"domain id {did} used by both '{seen_ids[did]}' and '{name}'")
        if did > 0xFFFF:
            die(f"domain id {did} ('{name}') exceeds u16")
        seen_ids[did] = name

    # --- assign local code ids (1..N per domain, file order) ----------------
    # packed_entries: list of (const_name, domain_id, local_code, name_str, desc)
    packed = []
    for dname, d in domains.items():
        did = int(d["id"])
        for i, code in enumerate(d.get("codes") or []):
            local = i + 1
            if local > 0xFFFF:
                die(f"domain '{dname}' has too many codes")
            const = f"WASMOS_ERR_{dname.upper()}_{code['name']}"
            label = f"{dname}.{code['name']}"
            packed.append((const, did, local, label, code.get("description", label)))

    out = []
    w = out.append

    w("/*")
    w(" * GENERATED by scripts/gen_abi_errors.py from abi/errors.yaml — DO NOT EDIT.")
    w(
        " * Edit the IDL and regenerate; see docs/architecture/34-abi-idl-and-error-model.md."
    )
    w(" */")
    w("#ifndef WASMOS_STATUS_H")
    w("#define WASMOS_STATUS_H")
    w("")
    w("#include <stdint.h>")
    w("#include <stdbool.h>")
    w("#include <stddef.h>")
    w("")
    w(f"#define WASMOS_ABI_ERRORS_VERSION {version}u")
    w("")

    # --- transport axis -----------------------------------------------------
    w("/* Transport / kernel-IPC result axis: did the call mechanism work. */")
    w("typedef int32_t wasmos_status_t;")
    w("enum {")
    for t in transport:
        w(
            f"    WASMOS_{t['name']} = {int(t['value'])}, /* {c_str(t.get('description',''))} */"
        )
    w("};")
    w("")

    # --- domain registry ----------------------------------------------------
    w("/* Domain registry: stable ids, assigned only in the IDL. */")
    w("typedef uint16_t wasmos_error_domain_t;")
    w("enum {")
    for name, d in domains.items():
        w(
            f"    WASMOS_ERR_DOMAIN_{name.upper()} = {int(d['id'])}, /* {c_str(d.get('description',''))} */"
        )
    w("};")
    w("")

    # --- packed code type + accessors --------------------------------------
    w("/* A domain error packs (domain << 16) | local_code into 32 bits. */")
    w("typedef uint32_t wasmos_error_code_t;")
    w("#define WASMOS_ERR_MAKE(dom, code) \\")
    w(
        "    ((wasmos_error_code_t)(((uint32_t)(dom) << 16) | ((uint32_t)(code) & 0xFFFFu)))"
    )
    w("#define WASMOS_ERR_DOMAIN_OF(x) ((wasmos_error_domain_t)((uint32_t)(x) >> 16))")
    w("#define WASMOS_ERR_CODE_OF(x)   ((uint16_t)((uint32_t)(x) & 0xFFFFu))")
    w("#define WASMOS_ERR_NONE ((wasmos_error_code_t)0u) /* success / empty frame */")
    w("")

    # --- packed code constants ---------------------------------------------
    w("/* Packed domain error constants (use with wasmos_error_is / _as). */")
    w("enum {")
    for const, did, local, _label, desc in packed:
        w(
            f"    {const} = WASMOS_ERR_MAKE(WASMOS_ERR_DOMAIN_{[n for n,dd in domains.items() if int(dd['id'])==did][0].upper()}, {local}), /* {c_str(desc)} */"
        )
    w("};")
    w("")

    # --- fixed error object -------------------------------------------------
    w(f"#define WASMOS_ERR_CHAIN_DEPTH {CHAIN_DEPTH}")
    w("#define WASMOS_ERR_FLAG_TRUNCATED (1u << 0)")
    w("")
    w(
        "/* One cause-chain frame: 8 bytes. domain==0 marks an empty/terminating slot. */"
    )
    w("typedef struct {")
    w("    uint16_t domain;")
    w("    uint16_t code;")
    w("    uint32_t origin; /* producing pid/context, 0 if none */")
    w("} wasmos_frame_t;")
    w("")
    w(
        "/* Fixed, always-carried error object (transport axis + reserved cause chain). */"
    )
    w("typedef struct {")
    w("    wasmos_status_t transport;")
    w("    uint32_t        flags;")
    w("    wasmos_frame_t  chain[WASMOS_ERR_CHAIN_DEPTH];")
    w("} wasmos_error_t;")
    w("")
    w('_Static_assert(sizeof(wasmos_frame_t) == 8, "wasmos_frame_t must be 8 bytes");')
    w(
        f'_Static_assert(sizeof(wasmos_error_t) == {ERROR_OBJ_BYTES}, "wasmos_error_t must be {ERROR_OBJ_BYTES} bytes");'
    )
    w("")

    # --- name / description lookups (freestanding, no stdio) ----------------
    w("static inline const char *wasmos_status_str(wasmos_status_t s) {")
    w("    switch (s) {")
    for t in transport:
        w(f"    case WASMOS_{t['name']}: return \"{t['name']}\";")
    w('    default: return "UNKNOWN_STATUS";')
    w("    }")
    w("}")
    w("")
    w("static inline const char *wasmos_error_domain_name(wasmos_error_domain_t d) {")
    w("    switch (d) {")
    for name, d in domains.items():
        w(f'    case WASMOS_ERR_DOMAIN_{name.upper()}: return "{name}";')
    w('    default: return "unknown";')
    w("    }")
    w("}")
    w("")
    w('/* Human-readable "domain.CODE" identity for a packed code. */')
    w("static inline const char *wasmos_error_code_name(wasmos_error_code_t c) {")
    w("    switch (c) {")
    w('    case WASMOS_ERR_NONE: return "none";')
    for const, _did, _local, label, _desc in packed:
        w(f'    case {const}: return "{label}";')
    w('    default: return "unknown";')
    w("    }")
    w("}")
    w("")
    w("/* Static description of a packed code. */")
    w("static inline const char *wasmos_strerror(wasmos_error_code_t c) {")
    w("    switch (c) {")
    w('    case WASMOS_ERR_NONE: return "success";')
    for const, _did, _local, _label, desc in packed:
        w(f'    case {const}: return "{c_str(desc)}";')
    w('    default: return "unknown error";')
    w("    }")
    w("}")
    w("")

    # --- chain helpers (Go-style ergonomics over fixed value frames) --------
    w(HELPERS)

    w("#endif /* WASMOS_STATUS_H */")
    w("")
    return "\n".join(out)


HELPERS = r"""static inline void wasmos_error_init(wasmos_error_t *e) {
    e->transport = WASMOS_OK;
    e->flags = 0;
    for (int i = 0; i < WASMOS_ERR_CHAIN_DEPTH; ++i) {
        e->chain[i].domain = 0;
        e->chain[i].code = 0;
        e->chain[i].origin = 0;
    }
}

static inline bool wasmos_error_ok(const wasmos_error_t *e) {
    return e->transport == WASMOS_OK && e->chain[0].domain == 0;
}

/* Head (most recently wrapped) domain error, or WASMOS_ERR_NONE. */
static inline wasmos_error_code_t wasmos_error_head(const wasmos_error_t *e) {
    return WASMOS_ERR_MAKE(e->chain[0].domain, e->chain[0].code);
}

/* Root cause: the deepest non-empty frame. */
static inline wasmos_error_code_t wasmos_error_root(const wasmos_error_t *e) {
    int i = 0;
    while (i + 1 < WASMOS_ERR_CHAIN_DEPTH && e->chain[i + 1].domain != 0) {
        ++i;
    }
    return WASMOS_ERR_MAKE(e->chain[i].domain, e->chain[i].code);
}

/* errors.Unwrap: the next cause after the head, or WASMOS_ERR_NONE. */
static inline wasmos_error_code_t wasmos_error_unwrap(const wasmos_error_t *e) {
    if (WASMOS_ERR_CHAIN_DEPTH < 2 || e->chain[1].domain == 0) {
        return WASMOS_ERR_NONE;
    }
    return WASMOS_ERR_MAKE(e->chain[1].domain, e->chain[1].code);
}

/* errors.Is: true if any frame matches the sentinel packed code. */
static inline bool wasmos_error_is(const wasmos_error_t *e, wasmos_error_code_t sentinel) {
    for (int i = 0; i < WASMOS_ERR_CHAIN_DEPTH; ++i) {
        if (e->chain[i].domain == 0) {
            break;
        }
        if (WASMOS_ERR_MAKE(e->chain[i].domain, e->chain[i].code) == sentinel) {
            return true;
        }
    }
    return false;
}

/* errors.As: extract the local code of the first frame in `dom`. */
static inline bool wasmos_error_as(const wasmos_error_t *e, wasmos_error_domain_t dom,
                                   uint16_t *out_code) {
    for (int i = 0; i < WASMOS_ERR_CHAIN_DEPTH; ++i) {
        if (e->chain[i].domain == 0) {
            break;
        }
        if (e->chain[i].domain == dom) {
            if (out_code) {
                *out_code = e->chain[i].code;
            }
            return true;
        }
    }
    return false;
}

/* Set the head error, discarding any existing chain. */
static inline void wasmos_error_set(wasmos_error_t *e, wasmos_error_domain_t dom,
                                    uint16_t code, uint32_t origin) {
    wasmos_error_init(e);
    e->chain[0].domain = dom;
    e->chain[0].code = code;
    e->chain[0].origin = origin;
}

/* Wrap: push a new head frame, preserving the cause chain. On overflow the head
 * and the root cause are kept, a middle frame is dropped, and TRUNCATED is set. */
static inline void wasmos_error_wrap(wasmos_error_t *e, wasmos_error_domain_t dom,
                                     uint16_t code, uint32_t origin) {
    int last = WASMOS_ERR_CHAIN_DEPTH - 1;
    if (e->chain[last].domain != 0) {
        /* Full: keep the root (last), shift [0..last-2] down into [1..last-1]. */
        for (int i = last - 1; i >= 1; --i) {
            e->chain[i] = e->chain[i - 1];
        }
        e->flags |= WASMOS_ERR_FLAG_TRUNCATED;
    } else {
        for (int i = last; i >= 1; --i) {
            e->chain[i] = e->chain[i - 1];
        }
    }
    e->chain[0].domain = dom;
    e->chain[0].code = code;
    e->chain[0].origin = origin;
}

/* Render the chain as "domain: desc <- domain: desc ..." into buf (bounded,
 * NUL-terminated). Returns the number of characters written (excluding NUL).
 * Freestanding: no stdio. */
static inline size_t wasmos_strerror_chain(const wasmos_error_t *e, char *buf, size_t n) {
    size_t w = 0;
    if (n == 0) {
        return 0;
    }
    for (int i = 0; i < WASMOS_ERR_CHAIN_DEPTH; ++i) {
        if (e->chain[i].domain == 0) {
            break;
        }
        if (i > 0) {
            const char *sep = " <- ";
            while (*sep && w + 1 < n) {
                buf[w++] = *sep++;
            }
        }
        wasmos_error_code_t packed = WASMOS_ERR_MAKE(e->chain[i].domain, e->chain[i].code);
        const char *dom = wasmos_error_domain_name(e->chain[i].domain);
        while (*dom && w + 1 < n) {
            buf[w++] = *dom++;
        }
        const char *colon = ": ";
        while (*colon && w + 1 < n) {
            buf[w++] = *colon++;
        }
        const char *desc = wasmos_strerror(packed);
        while (*desc && w + 1 < n) {
            buf[w++] = *desc++;
        }
    }
    if (w == 0) {
        const char *ok = "success";
        while (*ok && w + 1 < n) {
            buf[w++] = *ok++;
        }
    }
    buf[w] = '\0';
    return w;
}
"""


def main():
    ap = argparse.ArgumentParser(description="Generate the wasmos error/status ABI.")
    ap.add_argument(
        "--check",
        action="store_true",
        help="fail if the on-disk header differs from the IDL",
    )
    ap.add_argument("--out", default=DEFAULT_OUT, help="output header path")
    args = ap.parse_args()

    try:
        idl = load_idl()
    except YamlUnavailable as exc:
        # In --check the guard is advisory: without PyYAML we cannot verify, so
        # skip rather than fail (the checked-in header still drives the build).
        if args.check:
            print(f"gen_abi_errors: skipping check ({exc})", file=sys.stderr)
            return
        die(str(exc))

    header = build(idl)

    if args.check:
        try:
            with open(args.out, "r", encoding="utf-8") as f:
                current = f.read()
        except FileNotFoundError:
            current = None
        if current != header:
            print(
                f"gen_abi_errors: {args.out} is stale; run scripts/gen_abi_errors.py",
                file=sys.stderr,
            )
            sys.exit(2)
        print(f"gen_abi_errors: {os.path.relpath(args.out, REPO_ROOT)} is up to date")
        return

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(header)
    print(f"gen_abi_errors: wrote {os.path.relpath(args.out, REPO_ROOT)}")


if __name__ == "__main__":
    main()
