#!/usr/bin/env python3
"""Generate the WASM/IPC opcode ABI from abi/opcodes.yaml.

Opcodes are the POSITIVE `type` field of ipc_message_t, owned per subsystem.
The IDL is the single source; consumers `#include` the generated enums
(`wasmos_driver_abi.h` for the core subsystems, and the per-service headers
`rtc_ipc.h`/`font_ipc.h`/`gfx_ipc.h` + `serial.c` for theirs). Negative
`*_ERR_*` codes live in abi/errors.yaml; flags/descriptor structs stay
hand-written in the per-service headers.

Generates:
  - abi/generated/c/wasmos_opcodes.h   per-subsystem opcode enums + subsystem-id
       constants + wasmos_opcode_name(subsystem_id, type) diagnostic lookup
  - abi/generated/docs/opcodes.md      per-subsystem reference tables
  - abi/generated/{rust,go,zig,assemblyscript}/wasmos_opcodes.*  per-language consts

See docs/architecture/34-abi-idl-and-error-model.md.

Opcode values are NOT globally unique — they are endpoint-scoped, so the same
value can appear in two subsystems (e.g. gfx and pm both at 0x200, font and
netdrv both at 0xA00). The per-subsystem enums reproduce that faithfully, and
the name lookup is subsystem-scoped (the caller passes the subsystem the
endpoint speaks) so it is exact rather than best-effort.

Usage:
    gen_abi_opcodes.py [--check] [--verify-source]
      (no args)        regenerate all generated opcode files
      --check          fail (exit 2) if any on-disk file differs from the IDL
      --verify-source  fail (exit 3) if the IDL does not reproduce the live
                       opcode enums in wasmos_driver_abi.h (symbol -> value)
"""

import argparse
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IDL_PATH = os.path.join(REPO_ROOT, "abi", "opcodes.yaml")
GEN_C_DIR = os.path.join(REPO_ROOT, "abi", "generated", "c")
GEN_DOCS_DIR = os.path.join(REPO_ROOT, "abi", "generated", "docs")
OPCODES_H = os.path.join(GEN_C_DIR, "wasmos_opcodes.h")
OPCODES_MD = os.path.join(GEN_DOCS_DIR, "opcodes.md")

RPC_WASM_OUT = os.path.join(GEN_C_DIR, "wasmos_rpc_wasm.h")

GEN_ROOT = os.path.join(REPO_ROOT, "abi", "generated")
AS_RPC_OUT = os.path.join(GEN_ROOT, "assemblyscript", "wasmos_rpc.ts")
RUST_OUT = os.path.join(GEN_ROOT, "rust", "wasmos_opcodes.rs")
GO_OUT = os.path.join(GEN_ROOT, "go", "wasmos_opcodes.go")
ZIG_OUT = os.path.join(GEN_ROOT, "zig", "wasmos_opcodes.zig")
AS_OUT = os.path.join(GEN_ROOT, "assemblyscript", "wasmos_opcodes.ts")

DRIVER_ABI_H = os.path.join(
    REPO_ROOT, "src", "drivers", "include", "wasmos_driver_abi.h"
)


def die(msg, code=1):
    print(f"gen_abi_opcodes: {msg}", file=sys.stderr)
    sys.exit(code)


class YamlUnavailable(RuntimeError):
    pass


def load_idl():
    try:
        import yaml
    except ImportError as exc:
        raise YamlUnavailable(
            "PyYAML is required to regenerate the opcode ABI (pip install pyyaml); "
            "the checked-in generated files are used for normal builds."
        ) from exc
    with open(IDL_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


class Model:
    def __init__(self, idl):
        self.version = int(idl["abi_version"])
        self.subsystems = idl["subsystems"]

        seen_id, seen_sym = {}, {}
        for s in self.subsystems:
            sid = int(s["id"])
            if sid in seen_id:
                die(f"duplicate subsystem id {sid}: {seen_id[sid]} and {s['name']}")
            seen_id[sid] = s["name"]
            vals = {}
            for o in s["opcodes"]:
                v = int(o["value"])
                if v in vals:
                    die(
                        f"{s['name']}: duplicate value {hex(v)}: {vals[v]} and {o['symbol']}"
                    )
                vals[v] = o["symbol"]
                if o["symbol"] in seen_sym:
                    die(f"duplicate opcode symbol {o['symbol']}")
                seen_sym[o["symbol"]] = v
        # subsystem ids dense 0..N-1
        n = len(self.subsystems)
        missing = [i for i in range(n) if i not in seen_id]
        if missing:
            die(f"subsystem id space has gaps: missing {missing}")
        self.by_id = [
            next(s for s in self.subsystems if int(s["id"]) == i) for i in range(n)
        ]
        self.symbols = seen_sym

    @staticmethod
    def value(o):
        return int(o["value"])


BANNER = [
    "/*",
    " * GENERATED by scripts/gen_abi_opcodes.py from abi/opcodes.yaml — DO NOT EDIT.",
    " * See docs/architecture/34-abi-idl-and-error-model.md.",
    " */",
]


def _doc_block(text, indent):
    if not text:
        return []
    lines = text.rstrip("\n").split("\n") if isinstance(text, str) else list(text)
    if len(lines) == 1:
        return [f"{indent}/* {lines[0]} */"]
    out = [f"{indent}/* {lines[0]}"]
    out += [f"{indent} * {ln}".rstrip() for ln in lines[1:]]
    out.append(f"{indent} */")
    return out


def emit_opcodes_h(m):
    o = list(BANNER)
    w = o.append
    w("#ifndef WASMOS_GENERATED_OPCODES_H")
    w("#define WASMOS_GENERATED_OPCODES_H")
    w("")
    w("#include <stdint.h>")
    w("")
    w("/* Per-subsystem IPC opcode enums (positive ipc_message_t `type` values).")
    w(" * Values are endpoint-scoped and may repeat across subsystems. */")
    for s in m.by_id:
        lo = min(m.value(op) for op in s["opcodes"])
        hi = max(m.value(op) for op in s["opcodes"])
        w("")
        w(f"/* {s['name']} (0x{lo:X}..0x{hi:X}) */")
        w("enum {")
        for op in s["opcodes"]:
            o.extend(_doc_block(op.get("doc"), "    "))
            w(f"    {op['symbol']} = 0x{m.value(op):X},")
        w("};")
    # Subsystem ids, so the name lookup can be scoped. Opcode values are
    # endpoint-scoped and reuse ranges across subsystems (e.g. gfx and pm both at
    # 0x200), so a *global* value->name table would mislabel; the caller passes
    # the subsystem it is speaking.
    w("")
    w("/* Subsystem ids for wasmos_opcode_name(). */")
    w("enum {")
    for s in m.by_id:
        w(f"    WASMOS_OPCODE_SUBSYS_{s['name'].upper()} = {int(s['id'])},")
    w("};")
    w("")
    w("/* Opcode -> symbol name within a subsystem (diagnostics/logging). Pass the")
    w(" * WASMOS_OPCODE_SUBSYS_* the endpoint speaks; values are endpoint-scoped so")
    w(" * a subsystem-scoped lookup is exact, unlike a global one. */")
    w(
        "static inline const char* wasmos_opcode_name(uint32_t subsystem_id, uint32_t type) {"
    )
    w("    switch (subsystem_id) {")
    for s in m.by_id:
        w(f"    case WASMOS_OPCODE_SUBSYS_{s['name'].upper()}:")
        w("        switch (type) {")
        for op in s["opcodes"]:
            w(f'        case 0x{m.value(op):X}: return "{op["symbol"]}";')
        w('        default: return "UNKNOWN";')
        w("        }")
    w('    default: return "UNKNOWN";')
    w("    }")
    w("}")
    w("")
    w("#endif /* WASMOS_GENERATED_OPCODES_H */")
    w("")
    return "\n".join(o)


def emit_opcodes_md(m):
    o = [
        "<!-- GENERATED by scripts/gen_abi_opcodes.py from abi/opcodes.yaml — DO NOT EDIT. -->",
        "# WASMOS IPC Opcodes",
        "",
        "Positive `ipc_message_t.type` values, owned per subsystem. Values are",
        "endpoint-scoped and may repeat across subsystems.",
        "",
    ]
    for s in m.by_id:
        lo = min(m.value(op) for op in s["opcodes"])
        hi = max(m.value(op) for op in s["opcodes"])
        o.append(f"## {s['name']} (0x{lo:X}–0x{hi:X})")
        o.append("")
        o.append("| Opcode | Value | Kind | Description |")
        o.append("|---|---|---|---|")
        for op in s["opcodes"]:
            doc = op.get("doc") or ""
            if not isinstance(doc, str):
                doc = " ".join(doc)
            doc = doc.replace("\n", " ").replace("|", "\\|")
            o.append(
                f"| `{op['symbol']}` | 0x{m.value(op):X} | {op.get('kind','')} | {doc} |"
            )
        o.append("")
    return "\n".join(o)


_GEN = "GENERATED by scripts/gen_abi_opcodes.py from abi/opcodes.yaml — DO NOT EDIT."
_REF = "See docs/architecture/34-abi-idl-and-error-model.md."


def _doc_lines(text, prefix):
    if not text:
        return []
    lines = text.rstrip("\n").split("\n") if isinstance(text, str) else list(text)
    return [f"{prefix} {ln}".rstrip() for ln in lines]


def _lang(m, hdr, subsystem_fmt, const_fmt, doc_prefix):
    """Shared per-language emitter: opcode constants grouped by subsystem, each
    keeping the exact C symbol name (greppable/consistent across languages)."""
    o = [f"// {_GEN}", f"// {_REF}", ""] + list(hdr)
    for s in m.by_id:
        lo = min(m.value(op) for op in s["opcodes"])
        hi = max(m.value(op) for op in s["opcodes"])
        o.append("")
        o.append(subsystem_fmt(s["name"], lo, hi))
        for op in s["opcodes"]:
            o.extend(_doc_lines(op.get("doc"), doc_prefix))
            o.append(const_fmt(op["symbol"], m.value(op)))
    o.append("")
    return "\n".join(o)


def emit_rust(m):
    return _lang(
        m,
        ["#![allow(dead_code)]"],
        lambda n, lo, hi: f"// {n} (0x{lo:X}..0x{hi:X})",
        lambda sym, v: f"pub const {sym}: i32 = 0x{v:X};",
        "///",
    )


def emit_go(m):
    return _lang(
        m,
        ["package wasmos"],
        lambda n, lo, hi: f"// {n} (0x{lo:X}..0x{hi:X})",
        lambda sym, v: f"const {sym} int32 = 0x{v:X}",
        "//",
    )


def emit_zig(m):
    return _lang(
        m,
        [],
        lambda n, lo, hi: f"// {n} (0x{lo:X}..0x{hi:X})",
        lambda sym, v: f"pub const {sym}: i32 = 0x{v:X};",
        "///",
    )


def emit_as(m):
    return _lang(
        m,
        [],
        lambda n, lo, hi: f"// {n} (0x{lo:X}..0x{hi:X})",
        lambda sym, v: f"export const {sym}: i32 = 0x{v:X};",
        "//",
    )


def emit_rpc_wasm(m):
    """Typed future-returning request/reply client stubs (wasm) over the libsys
    ipc-future bridge, for opcodes that declare `rpc:` in the IDL (Phase 3c
    proof-of-concept). Included from a wasm app/service (which has the libsys -I).
    """
    o = list(BANNER)
    w = o.append
    w("#ifndef WASMOS_GENERATED_RPC_WASM_H")
    w("#define WASMOS_GENERATED_RPC_WASM_H")
    w("")
    w('#include "wasmos/libsys.h"  /* ipc-future bridge + the opcode enums */')
    w("")
    w("/* Each stub inits a caller-owned ipc-future op with a generated reply-status")
    w(" * decoder, sends the request, and returns the future. request/reply_args map")
    w(" * to arg0..argN in order; bit-level packing stays hand-written. */")
    for s in m.by_id:
        for op in s["opcodes"]:
            rpc = op.get("rpc")
            if not rpc:
                continue
            base = op["symbol"].lower()
            if base.endswith("_req"):
                base = base[:-4]
            req_args = rpc.get("request") or []
            reply_args = rpc.get("reply_args") or []
            if len(req_args) > 4 or len(reply_args) > 4:
                die(f"{op['symbol']}: rpc request/reply_args exceed 4 arg words")
            reply_sym, err_sym = rpc["reply"], rpc.get("error")
            w("")
            w("typedef struct {")
            for a in reply_args:
                w(f"    int32_t {a};")
            if not reply_args:
                w("    int32_t _unused;")
            w(f"}} {base}_reply_t;")
            w(f"static inline int32_t {base}_reply_status(void* user,")
            w(
                "                                          const wasmos_ipc_message_t* r) {"
            )
            w(f"    {base}_reply_t* out = ({base}_reply_t*)user;")
            if err_sym:
                w(f"    if (r->type == {err_sym}) return r->arg0 ? r->arg0 : -1;")
            w(f"    if (r->type != {reply_sym}) return -1;")
            if reply_args:
                w("    if (out) {")
                for i, a in enumerate(reply_args):
                    w(f"        out->{a} = r->arg{i};")
                w("    }")
            else:
                w("    (void)out;")
            w("    return 0;")
            w("}")
            params = [
                "wasmos_sys_event_loop_t* loop",
                "wasmos_sys_wasm_ipc_future_t* op",
                "int32_t dest_endpoint",
                "int32_t reply_endpoint",
            ]
            params += [f"int32_t {a}" for a in req_args]
            params += [f"{base}_reply_t* out_reply", "int32_t* out_request_id"]
            argvals = [req_args[i] if i < len(req_args) else "0" for i in range(4)]
            w(f"static inline wasmos_future_t* wasmos_rpc_{base}(")
            w("        " + ", ".join(params) + ") {")
            w(
                f"    wasmos_sys_wasm_ipc_future_init(op, {base}_reply_status, out_reply);"
            )
            w(
                "    return wasmos_sys_wasm_ipc_future_send(loop, op, dest_endpoint, reply_endpoint,"
            )
            w(
                f"        {op['symbol']}, {argvals[0]}, {argvals[1]}, {argvals[2]}, {argvals[3]},"
            )
            w("        out_request_id);")
            w("}")
    w("")
    w("#endif /* WASMOS_GENERATED_RPC_WASM_H */")
    w("")
    return "\n".join(o)


def _rpc_ops(m):
    """(subsystem, opcode) pairs that declare an `rpc:` stub, in id order."""
    return [(s, op) for s in m.by_id for op in s["opcodes"] if op.get("rpc")]


def _rpc_base(op):
    b = op["symbol"].lower()
    return b[:-4] if b.endswith("_req") else b


def _camel(base, upper_first):
    parts = base.split("_")
    out = "".join(p[:1].upper() + p[1:] for p in parts)
    return out if upper_first else out[:1].lower() + out[1:]


def emit_rpc_as(m):
    """AssemblyScript typed request/reply client stubs (Phase 3c PoC). AS has no
    future bridge, so these are synchronous wrappers over ipc.call (the idiom
    date.ts uses). Drop into an AS app project alongside wasmos.ts +
    wasmos_opcodes.ts."""
    ops = _rpc_ops(m)
    imports = sorted(
        {op["symbol"] for _, op in ops}
        | {op["rpc"]["reply"] for _, op in ops}
        | {op["rpc"]["error"] for _, op in ops if op["rpc"].get("error")}
    )
    o = [
        "// GENERATED by scripts/gen_abi_opcodes.py from abi/opcodes.yaml — DO NOT EDIT.",
        "// See docs/architecture/34-abi-idl-and-error-model.md.",
        "",
        'import { ipc } from "./wasmos";',
        "import {",
    ]
    o += [f"    {sym}," for sym in imports]
    o += ['} from "./wasmos_opcodes";', ""]
    for _s, op in ops:
        base = _rpc_base(op)
        rpc = op["rpc"]
        req = rpc.get("request") or []
        rep = rpc.get("reply_args") or []
        if len(req) > 4 or len(rep) > 4:
            die(f"{op['symbol']}: rpc request/reply_args exceed 4 arg words")
        cls = _camel(base, True) + "Reply"
        fn = _camel(base, False)
        o.append(f"export class {cls} {{")
        for a in rep:
            o.append(f"    {a}: i32 = 0;")
        if not rep:
            o.append("    _unused: i32 = 0;")
        o.append("}")
        # request args -> function params; fill arg0..3
        argvals = [req[i] if i < len(req) else "0" for i in range(4)]
        params = ["server: i32"] + [f"{a}: i32" for a in req] + [f"out: {cls}"]
        o.append(f"export function {fn}({', '.join(params)}): i32 {{")
        o.append(
            f"    const reply = ipc.call(server, {op['symbol']}, "
            f"{argvals[0]}, {argvals[1]}, {argvals[2]}, {argvals[3]});"
        )
        o.append("    if (reply == null) return -1;")
        if rpc.get("error"):
            o.append(
                f"    if (reply.type == {rpc['error']}) return reply.arg0 != 0 ? reply.arg0 : -1;"
            )
        o.append(f"    if (reply.type != {rpc['reply']}) return -1;")
        for i, a in enumerate(rep):
            o.append(f"    out.{a} = reply.arg{i};")
        o.append("    return 0;")
        o.append("}")
        o.append("")
    return "\n".join(o)


OUTPUTS = [
    (OPCODES_H, emit_opcodes_h),
    (OPCODES_MD, emit_opcodes_md),
    (RPC_WASM_OUT, emit_rpc_wasm),
    (AS_RPC_OUT, emit_rpc_as),
    (RUST_OUT, emit_rust),
    (GO_OUT, emit_go),
    (ZIG_OUT, emit_zig),
    (AS_OUT, emit_as),
]


def _read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def verify_source(m):
    """Assert the live wasmos_driver_abi.h opcode enums (positive values in
    0x100..0xCFF) reproduce the IDL symbol->value map exactly. Self-skips once
    the header is swapped to #include the generated enums."""
    text = _read(DRIVER_ABI_H)
    if "wasmos_opcodes.h" in text:
        print(
            "gen_abi_opcodes: header already swapped to the generated enums; --check guards it"
        )
        return
    src = {
        sym: int(val, 16)
        for sym, val in re.findall(r"([A-Z][A-Z0-9_]+)\s*=\s*(0x[0-9A-Fa-f]+)", text)
        if 0x100 <= int(val, 16) <= 0xCFF
    }
    problems = []
    if set(src) != set(m.symbols):
        problems.append(
            f"opcode symbol set differs: only-src={sorted(set(src) - set(m.symbols))} "
            f"only-idl={sorted(set(m.symbols) - set(src))}"
        )
    for sym in set(src) & set(m.symbols):
        if src[sym] != m.symbols[sym]:
            problems.append(
                f"value mismatch {sym}: src=0x{src[sym]:X} idl=0x{m.symbols[sym]:X}"
            )
    if problems:
        for p in problems:
            print(f"gen_abi_opcodes: {p}", file=sys.stderr)
        die(
            "IDL does not match the live opcode enums — reconcile before generating",
            code=3,
        )
    print(
        f"gen_abi_opcodes: IDL verified against wasmos_driver_abi.h "
        f"({len(m.symbols)} opcodes across {len(m.subsystems)} subsystems)"
    )


def main():
    ap = argparse.ArgumentParser(description="Generate the WASM/IPC opcode ABI.")
    ap.add_argument(
        "--check", action="store_true", help="fail if any generated file is stale"
    )
    ap.add_argument(
        "--verify-source", action="store_true", help="fail if the IDL ≠ the live enums"
    )
    args = ap.parse_args()

    try:
        model = Model(load_idl())
    except YamlUnavailable as exc:
        if args.check or args.verify_source:
            print(f"gen_abi_opcodes: skipping ({exc})", file=sys.stderr)
            return
        die(str(exc))

    if args.verify_source:
        verify_source(model)
        return

    if args.check:
        stale = False
        for path, emit in OUTPUTS:
            want = emit(model)
            have = _read(path) if os.path.exists(path) else None
            if have != want:
                print(
                    f"gen_abi_opcodes: {os.path.relpath(path, REPO_ROOT)} is stale",
                    file=sys.stderr,
                )
                stale = True
        if stale:
            die("run scripts/gen_abi_opcodes.py to regenerate", code=2)
        print("gen_abi_opcodes: all generated opcode files are up to date")
        return

    for path, emit in OUTPUTS:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(emit(model))
        print(f"gen_abi_opcodes: wrote {os.path.relpath(path, REPO_ROOT)}")


if __name__ == "__main__":
    main()
