if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
  message(FATAL_ERROR "generate_device_manager_manifest.cmake requires INPUT and OUTPUT")
endif()

file(READ "${INPUT}" CONTENTS)
string(REPLACE "\r\n" "\n" CONTENTS "${CONTENTS}")
string(REPLACE "\r" "\n" CONTENTS "${CONTENTS}")

set(DRIVER "")
set(CLASS "")
set(IO_PORT_MIN "")
set(IO_PORT_MAX "")
set(IRQ_MASK "")
set(CAP_IO_PORT "0")
set(CAP_IRQ "0")

string(REPLACE "\n" ";" LINES "${CONTENTS}")
foreach(LINE ${LINES})
  string(STRIP "${LINE}" LINE)
  if(LINE STREQUAL "" OR LINE MATCHES "^#")
    continue()
  endif()
  if(LINE MATCHES "^driver=(.+)$")
    set(DRIVER "${CMAKE_MATCH_1}")
  elseif(LINE MATCHES "^class=(.+)$")
    set(CLASS "${CMAKE_MATCH_1}")
  elseif(LINE MATCHES "^io_port_min=(.+)$")
    set(IO_PORT_MIN "${CMAKE_MATCH_1}")
  elseif(LINE MATCHES "^io_port_max=(.+)$")
    set(IO_PORT_MAX "${CMAKE_MATCH_1}")
  elseif(LINE MATCHES "^irq_mask=(.+)$")
    set(IRQ_MASK "${CMAKE_MATCH_1}")
  elseif(LINE MATCHES "^cap_io_port=(.+)$")
    set(CAP_IO_PORT "${CMAKE_MATCH_1}")
  elseif(LINE MATCHES "^cap_irq=(.+)$")
    set(CAP_IRQ "${CMAKE_MATCH_1}")
  endif()
endforeach()

if(NOT DRIVER STREQUAL "ata")
  message(FATAL_ERROR "ATA manifest must set driver=ata")
endif()
if(CLASS STREQUAL "" OR IO_PORT_MIN STREQUAL "" OR IO_PORT_MAX STREQUAL "" OR IRQ_MASK STREQUAL "")
  message(FATAL_ERROR "ATA manifest missing required fields")
endif()

file(WRITE "${OUTPUT}" "/* Auto-generated from configs/device_manager/ata.manifest. */\n")
file(APPEND "${OUTPUT}" "#ifndef WASMOS_DEVMGR_ATA_MANIFEST_H\n")
file(APPEND "${OUTPUT}" "#define WASMOS_DEVMGR_ATA_MANIFEST_H\n")
file(APPEND "${OUTPUT}" "#define ATA_MANIFEST_CLASS ${CLASS}\n")
file(APPEND "${OUTPUT}" "#define ATA_MANIFEST_CAP_IO_PORT ${CAP_IO_PORT}\n")
file(APPEND "${OUTPUT}" "#define ATA_MANIFEST_IO_PORT_MIN ${IO_PORT_MIN}\n")
file(APPEND "${OUTPUT}" "#define ATA_MANIFEST_IO_PORT_MAX ${IO_PORT_MAX}\n")
file(APPEND "${OUTPUT}" "#define ATA_MANIFEST_CAP_IRQ ${CAP_IRQ}\n")
file(APPEND "${OUTPUT}" "#define ATA_MANIFEST_IRQ_MASK ${IRQ_MASK}\n")
file(APPEND "${OUTPUT}" "#endif\n")
