version = 1

[boot]
bootstrap_modules = [
  "chardev-client",
  "init-smoke",
  "native-call-min",
  "native-call-smoke",
  "ata",
  "fs-fat",
  "device-manager",
]

[sysinit]
spawn = [
  "chardev-client",
  "vt",
  "cli",
]

[[entries]]
kind = "wasmos_app"
flags = ["bootstrap"]
path = "apps/chardev_client.wap"
source = "chardev_client.wap"

[[entries]]
kind = "wasmos_app"
flags = ["bootstrap"]
path = "apps/init_smoke.wap"
source = "init_smoke.wap"

[[entries]]
kind = "wasmos_app"
flags = ["bootstrap"]
path = "apps/native_call_min.wap"
source = "native_call_min.wap"

[[entries]]
kind = "wasmos_app"
flags = ["bootstrap"]
path = "apps/native_call_smoke.wap"
source = "native_call_smoke.wap"

[[entries]]
kind = "wasmos_app"
path = "apps/shmtgt.wap"
source = "shmtgt.wap"

[[entries]]
kind = "wasmos_app"
path = "apps/shmownr.wap"
source = "shmownr.wap"

[[entries]]
kind = "wasmos_app"
flags = ["bootstrap"]
path = "system/drivers/ata.wap"
source = "ata.wap"

[[entries]]
kind = "wasmos_app"
flags = ["bootstrap"]
path = "system/drivers/fs_fat.wap"
source = "fs_fat.wap"

[[entries]]
kind = "wasmos_app"
flags = ["bootstrap"]
path = "system/services/device_manager.wap"
source = "device_manager.wap"

[[entries]]
kind = "config"
path = "config/bootcfg.bin"
generated = "boot_config"
